### ISSUE TITLE
Cargo bug - IF loading cargo has been  issued and you cancel the task - task is in limbo state

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1000]
I f**ked up last night
1. I joined a infrantry cargo task 
2. A flew to the guys, landed
3. I ordered them to board
4. I f**ked up and hit cancel task by mistake

Result the guys ran over boarded, the task was aborted but because the guys were then inside and onboard my
heli I could not either join the task or get them to unboard

Rare case this is , but just logging it anyway

**Comment by FlightControl-User** [comment]
thanks for logging this @shadowze. This is a good one!

**Comment by baluballa** [comment]
@FlightControl-User what is status on this?

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In 14 Nov 2018 the last commit to Moose 2.4 stable was made on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
