### ISSUE TITLE
In DCS ME adding F10 menus for group breaks MOOSE Commander center menus (CC menu not visible)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1025]
My mission uses CC to handles tasks for helis
Menu for commanad center = ok
tried 2 things

1. Used in DCS ME Add radio command (this adds to everyone) a command called LOAD
it just sets a flag = this works fine BOTH CC menu and new single item radio command are visible

2.  Used in DCS ME Add radio command GROUP (this adds a specific group) a command called LOAD
it just sets a flag = this LOAD radio command is visible, the normal CC menu is gone :-(

Tested in ME then starting mission

**Comment by Delta-99** [comment]
This sounds like a DCS bug so marking it a possible bug here.

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In 14 Nov 2018 the last commit to Moose 2.4 stable was made on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
