### ISSUE TITLE
SPAWN:userflag

### ISSUE THREAD

**Issue by Prof-hilactic** [FlightControl-Master/MOOSE#103]
Could we have a new SPAWN initialisation method based on userflag?

if a flag # is true then spawn the new group 
spawn the units until flag # reach a set value or is set to false/true

**Comment by FlightControl-Master** [comment]
How would we implement this? Must I schedule a check every second?

**Comment by FlightControl-Master** [comment]
Prof. Why was this again?

**Comment by Grey-Echo** [comment]
I don't want to be rude, @Prof-hilactic hasn't contributed to anything on Github since he opened this issue. Since the feature request isn't clear and he isn't likely to precise it, I'm going to close this issue. @Prof-hilactic , if you are still interested in this feature, please open a new issue, and explain as clearly as you can what you want !
