### ISSUE TITLE
AI_FORMATION cannot be stopped

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#1045]
There is a FSM "*"-->"Stop"-->"Stopped" but it does not do anything. AI stays in formation since the Follow() command is still called.

**Comment by FlightControl-User** [comment]
Ok. Thank you. I also need to rework this. Instead of a leader pulling the group over the path, I think it is better to reallocate a route to the formation directly, and a leader vector is calculated based on the current time, route segments and speed of each route segment. This will ensure that the formation will kept together at all times. It also will allow the route can be changed dynamically. I have this for a long time in the back of my mind. I'll also fix that stop bug.

**Comment by funkyfranky** [comment]
Don't worry, I already fixed the stop bug. So don't waste your time on this :) I'll submit the fix in a bit. You can improve it, if necessary.

More importantly, before you rework the class, I'd like to mention that it is very useful when used in a more "creative" way, i.e. not as originally designed.

For example, I use this class to make a rescue helo fly in formation with an aircraft carrier. Also other ships can be in formation with a leading ship. All very useful!
See https://www.youtube.com/watch?time_continue=1&v=HRGuUEK-Wsg

In case you rework the class, it would be great if these features would still work!
