### ISSUE TITLE
WAREHOUSE: Integrate warehouse in AI_A2A_DISPATCHER (and later other dispatchers).

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#1047]
Let's see how we can integrate the WAREHOUSE into the dispatchers.
For this, I suggest we first clearly articulate the joint **requirement**. The community is invited to join this discussion. If we design something, let's first discuss what we wanna make, why and how we wanna design this.

**Comment by funkyfranky** [comment]
Just a quick comment about the capabilities of the warehouse:
Since the warehouse only spawns at airbases (not in air) it has a **very** sophisticated spawning algorithm.

The warehouse checks the availability of parking spots in advance. It will *only* spawn assets from a request if enough free parking spots for all requested assets are available. If the parking spot situation at the time is insufficient, no spawning will happen and the request will stay queued until enough free spots are available again. The warehouse routine also checks for the dimension of the planes so that even the biggest aircraft (think of B-52s) will only get parking spots so far apart from each other that the planes will not overlap.

What is not possible is that requests are split. So if one requests 20 aircraft in *one* request, there must be 20 free parking spots available at some point. It will not spawn only two aircraft when two spots are available and deduct that from the 20 which were initially requested. So a request must be reasonable to some extend.

For example:
We got an airport with 20 parking spots. You can make 100 requests for 4ship flights in one go. Only 5 will be spawned initially. Once the first 4 aircraft have left their parking position, the next request is processed and 4 new aircraft are spawned. And so on and so force until all 400 planes have safely left the airbase.

**Comment by thebgpikester** [comment]
OK, that's gonna be tough to work out. I think rather than my first suggestion, perhaps Dispatcher needs to scan the apron for airplanes and use what is there, since really WH is doing half of what I suggested in the first place. So the process would be (in this suggestion) make a self request THEN scan the aprons for the unactivated planes and use them.
I know I make this sound easy (to all reading that don't write as much perhaps) and it's not. I'm just trying to string the data flow together. But if we consider the "Customer Vision" this is what the customer might want; 
visible planes being pulled into combat by a warehouse system that tries to supply it.

**Comment by gunterlund** [comment]
chiming in here. What about limiting the number of aircraft to the slots period instead having 1 airport spawn in 100 aircraft which is not realistic somehow put in a hierarchy of airports with a master air port that would feed the proper count of aircraft to the receiving airport. This may be two difficult. The designer could assign a network of airbases so airbase 1 is the master and it feeds 2, 3 etc. but never more than the slots on the tarmac.

**Comment by gunterlund** [comment]
I also like the mission notation that FC has in dispatcher so you can see what aircraft are doing what assignment including their group name

**Comment by thebgpikester** [comment]
Not happening any time soon.
