### ISSUE TITLE
Designate errors about the menu

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1065]
Error in timer function: [string "Scripts/Moose/Core/Menu.lua"]:77: Parent path not found in menu index for group menu

Error in SCHEDULER function:[string "Scripts/Moose/Core/Message.lua"]:230: Parameter #1 (group id) missed

Error in timer function: [string "Scripts/Moose/Core/Menu.lua"]:884: Parameter #1 (group id) missed

**Comment by FlightControl-User** [comment]
I need more info on this. Can you resimulate this?

**Comment by Enfarda** [comment]
will try, 
but this happen more when more then 2 ppl are playing at same time

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In July 2019 the last stable MOOSE version was released on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
