### ISSUE TITLE
DESIGNATE: Doesn't lease the new target immediatly

### ISSUE THREAD

**Issue by PorcoRosso86** [FlightControl-Master/MOOSE#1068]
Like as title, function designate doesn't lease the new target immediatly after the previously is destroyed, but only after the standard lease time (120s as default)

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In July 2019 the last stable MOOSE version was released on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
