### ISSUE TITLE
AIB Only spawning one aircraft.

### ISSUE THREAD

**Issue by grandpaSam** [FlightControl-Master/MOOSE#1082]
Whenever I try to do the 2 clients 1 template example for the AI balancer only one aircraft will spawn and that aircraft will not do anything but sit on parking. 

The example im trying to use is AIB-001 Spawned AI. 
When I try to recreate the mission from scratch I get the same problem as the posted example.

According to this [video](https://www.youtube.com/watch?v=SS5MrYgQzwU&list=PL7ZUrU4zZUl2CJVIrL1TdAumuVS8n64B7&index=2) I should be getting 2 spawned aircraft that fly to waypoints.

**Comment by thebgpikester** [comment]
Impossible to understand without more data, how many airplanes in the template group, is the single client replacing the group of two or a group of one? it could well be expected behaviour depending on your configuration, can you post the mission or, better, discuss in Discord first so we can understand more clearly?

**Comment by thebgpikester** [comment]
no updates for a year. archiving
