### ISSUE TITLE
Deactivation of parked and "stuck" AI  on Balancer

### ISSUE THREAD

**Issue by HubJack** [FlightControl-Master/MOOSE#110]
After AI have done their task they land and park just fine but never deactivate. I suggest a cleanup routine that cleans out parked AI when speed is 0. TAG the aircraft as finished with task so you don't terminate AI that is holding short waiting for other aircraft's to land. The same function can be done on AI that is stuck on airport (two AI meeting) but there you have the same problem for not removing waiting aircraft's holding short. You can possibly remove "stuck" aircraft's after like one minute if they don't have the TAG that they have finished their task. Some functions to make this work but I believe it is possible.

**Comment by FlightControl-Master** [comment]
What I think we can do is to use as part of the spawning the"cleanup" api of the SPAWN class. CleanUp cleans units on hold for more than x seconds automatically... I think this is a small fix in the AIBALANCER class that anybody can implement.... Who is a candidate to do this?

**Comment by afinegan** [comment]
What I found so far in the AIBalancer cleanup, the Cleanup(60) is cleaning up the new spawns but not the old (which are probably created in the AIBalancer script), problem is, the planes that currently land and make it back into the hanger, sit and never regenerate so I am trying to apply :InitRepeatOnLanding():InitRepeatOnEngineShutDown() type logic to it atm. - due to me being new to the code base, any suggestions are welcome lol

**Comment by FlightControl-Master** [comment]
Ok. So the CleanUp(60) is working then? 
Try to add in PATROLZONE, everywhere there is a SPAWN:New call, to add there :InitRepeatOnEngineShutdown().
Please let us know how that goes!

Sven

**Comment by FlightControl-Master** [comment]
Solved. Check AI_BALANCER.
