### ISSUE TITLE
AI_A2A_Dispatcher - Enhancements

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#1117]
The following are enhancements to the AI_A2A_Dispatcher allowing for some sqn management to take place I would do a pull request on it but some reason when I try and make a branch and sub i get told i don't have permissions (think my contrib wasn't moved to the new areas).

```
--- Reinforce's a Squadrons by a set amount adding it to the current Squadron resource count.
--@param Squadron Name - String the name of the squadron that is to be given new units
--@param amount - Int, the amount to add to the squadron.
 function AI_A2A_DISPATCHER:ReinforceSquadron( SquadronName, Amount )
    DefenderSquadron = self:GetSquadron( SquadronName )
    if DefenderSquadron.ResourceCount then
      DefenderSquadron.ResourceCount = DefenderSquadron.ResourceCount + Amount
    end
    self:F( { Squadron = DefenderSquadron, SquadronResourceCount = DefenderSquadron.ResourceCount } )
  end


--- Reduces a Squadron by a set amount, but also checkks that you haven't reduced it below 0
--@param Squadron Name - String the name of the squadron that is to be given new units
--@param amount - Int, the amount to remove from the squadron.
function AI_A2A_DISPATCHER:ReduceSquadron( SquadronName, Amount )
    DefenderSquadron = self:GetSquadron( SquadronName )
    if DefenderSquadron.ResourceCount >= Amount then
      DefenderSquadron.ResourceCount = DefenderSquadron.ResourceCount - Amount
   else
     DefenderSquadron.ResourceCount = 0
    end
    self:F( { Squadron = DefenderSquadron, SquadronResourceCount = DefenderSquadron.ResourceCount } )
  end
--- Returns the current Squadron Strength 
-- @param Squadron Name - String the name of the squadron
-- Returns Int
 function AI_A2A_DISPATCHER:GetSquadronAmount( SquadronName)
    DefenderSquadron = self:GetSquadron( SquadronName )
        self:F( { Squadron = DefenderSquadron, SquadronResourceCount = DefenderSquadron.ResourceCount } )
    return DefenderSquadron.ResourceCount 
  end```

**Comment by thebgpikester** [comment]
I work round this by turning them off and on as conditionals. Whilst yours is a solution, I can add a greater variety of conditionals than pure numbers, such as what bases i've currently captured, events during mission play, or timed surprises etc. I think, and it's my opinion, so don't feel im squashing this, that over engineering the conditional part of A2A_Dispatcher isn't needed, we have so many toys to play with and easy ways to do it in more complex ways.
if shithappens then 2ADispatcher:SetSquadron( "Abbas Lengeh", "Bandar Abbas Intl", ( SquadronTemplate_Abbas_CAP ) ,0)
end

if goodhappens then 2ADispatcher:SetSquadron( "Abbas Lengeh", "Bandar Abbas Intl", ( SquadronTemplate_Abbas_CAP ) )
end  

Works great ;)

**Comment by robgrahamau** [comment]
Pike I don't agree because what your forgetting is that you can have something dynamic happen, lets say you have simulated a bunch of fuel supplies and each one of those should remove 1, just 1 unit of the A2G or A2A system from being active under the current system you have to 

get the CURRENT squadron amount, then rewrite the entire squadron hope that something else doesn't happen in the scheduler etc etc etc.

with the addition i've proposed there and AM using in my own scripts and WOULD have added myself into the code base if my permissions where not screwed you simply tell it add x or remove x you can still go 'ok kill the entire squadron' your way if you want but this stops it being messy and for NIL or the like to creep in. 

This also allows for things like  Factory simulation to take place or to extend the warehouse simulation were your able to say ok this warehouse has requsted x from y location when that Arrives add it to the squadron and remove it from the warehouse.. OR vise versa.. this WAREHOUSE is requesting 5 Mig 29 from X squadron first off does it even have 5? if so then I want 5 so reduce it add them to the warehouse and send them to the other warehouse etc.

Rewriting an ENTIRE squadron should **never** be the go to option as it can lead to a mass of errors creeping in.

**Comment by thebgpikester** [comment]
Ah, but the thing you are not seeing is that you don't rewrite the "ENTIRE" squadron, you simply call one line on it's own: 
A2ADispatcher:SetSquadron( "Abbas Lengeh", "Bandar Abbas Intl", ( SquadronTemplate_Abbas_CAP ), **MyVariableHere** )
Which is fundamentally no different in effect and i've doneover 200 days (thousands of hours) public server play testing, writing that in a schedule on a live public server. No NIL's, no ill effects and I've got a video on how to use it also, you can also change borders, group sizes and everything. You call the dispatcher in entirety once and update the relevant lines in a scheduler
I've not disagreed with you because the use case is great, we wouldn't both be using it otherwise. ;)
I'm simply stating that it's over engineered for achieving the same effect without compromise and the same technique can be applied additionally to moving the border, changing the group sizes or indeed any element of the config.

Example https://youtu.be/tfrdOMJSo6s from January.

**Comment by thebgpikester** [comment]
The only thing left here is to try to sort out branches in moose and forks and that is completely up in the air, we dont have the admin control to even do that :(. Enhancements in forks and on their own arent going anywhere because FC has moved on. So archiving this until  we get the ability to fork.
