### ISSUE TITLE
SET_BASE:FindNearestAirbaseFromPointVec2 returns error

### ISSUE THREAD

**Issue by EXit77** [FlightControl-Master/MOOSE#1131]
I get an error on...
`BLUECAPZoneWestVec2 = BLUECAPZoneWest:GetRandomPointVec2()
BLUEAirbaseCAPZoneWestSet:FindNearestAirbaseFromPointVec2( BLUECAPZoneWestVec2 )`

Error Log:
`2019-03-17 01:11:44.639 ERROR   DCS: Mission script error: : [string "C:\Users\USER\AppData\Local\Temp\DCS/~mis00002ADD.lua"]:19448: attempt to perform arithmetic on field 'z' (a nil value)`

**Comment by baluballa** [comment]
Cannot reproduce error. Have checked the FindNearestAirbaseFromPointVec2 and for sure it returns nearest AB.

What version of Moose are you using?

Wingthor

**Comment by EXit77** [comment]
Version is 2.4.13
Code wich produces the error:
```
BLUECAPZoneWest = ZONE_POLYGON:New( "BLUE CAP Zone West", GROUP:FindByName( "BLUE CAP Zone West" ) )
BLUECAPZoneWestVec2 = BLUECAPZoneWest:GetRandomPointVec2()
BLUEAirbaseCAPZoneWestSet = SET_AIRBASE:New():FilterCoalitions("blue"):FilterStart()
BLUEAirbaseCAPZoneWestSet:Flush()
BLUEAirbaseCAPZoneWestSet:FindNearestAirbaseFromPointVec2( BLUECAPZoneWestVec2 )
BLUEAirbaseCAPZoneWestSet:ForEachAirbase(
  function (Airbase)
    local BLUEAirbaseName = Airbase:GetName()
    BLUEAirbaseName = string.gsub(BLUEAirbaseName, '-', '_')
    BLUEAirbaseName = string.gsub(BLUEAirbaseName, ' ', '_')
    MESSAGE:New("Nearest Airbase to CAP-Zone-West: "..BLUEAirbaseName, 30):ToAll()
  end
)
```

**Comment by thebgpikester** [comment]
Nearest airbase I've tested many times. The only issues are FARPS and OILRIGS which causes issues due to a DCS bug with getByName() on farps returning nil.

Considering there is no referenced mission and no way to know what the exact config is in the lsit of airbases and no updates for nearly a year, I am archiving this. Pick it up in Discord if you have a reproducible miz and we can reopen this.
