### ISSUE TITLE
SET_UNIT not working correctly for certain FilterPrefix

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1176]
have 3 helis with the group name the same as the unit name as listed here:
Tran sea -1.1 MI-8
Tran sea -1.2 MI-8
Tran sea -1.4 MI-8 CSAR

I tried using "Tran sea -1"   as the FilterPrefix but it is returning 0 for the count

Debug code 
SCHEDULER:New( nil, function()
drop_heli = SET_UNIT:New():FilterPrefixes("Tran sea -1"):FilterOnce()
    local msg = "Count of SET_UNITS is ".. drop_heli:Count() 
    MESSAGE:New( msg, 3):ToAll()
end, {}, 6, 4 , nil , nil )

Weird thing is if I use SET_GROUP it works ? Are there some "special" characters you are not allowed to use in the unit name ?
[unit_bug_test.zip](https://github.com/FlightControl-Master/MOOSE/files/3353619/unit_bug_test.zip)

See attached test mission file

**Comment by thebgpikester** [comment]
SET_UNIT and SET_CLIENT (unitname) FilterPrefixes() seem to parse out special characters, where GROUP SET's do not:

UNIT/CLIENT:
:FilterPrefixes("Tran sea -1") --doesnt work
 "Tran_sea-1" --doesnt work
Tran-sea --doesnt work
TranSea-1- --doesnt work
TranSea1  --works

SET_GROUP Filters can include multiple hyphens like "Tran-sea-1" and they all work

So seems to be a logical inconsistency, but perhaps this parsing of special characters is part of something else required like where we declare objects directly into the mission or declare CARGO especially or ZONES.

If this is required by design then special warnings need to be in place so as not to confuse people.

**Comment by funkyfranky** [comment]
Yeah, looks like there is a difference.
SET_GROUP filters like
`if string.find( MGroup:GetName(), GroupPrefix:gsub ("-", "%%-"), 1 ) then`
Whereas the others filter like
`if string.find( MUnit:GetName(), UnitPrefix, 1 ) then`
Don't know if this intentional or an omission.

**Comment by Loophole62ndFF** [comment]
"-" is a special character (like "+" and "*" and a number of others) when used in Lua "Patterns" (the Lua equivalent of Regular Expressions).  The "pattern" argument to string.find, string.gmatch, string.gsub, and string.match are all interpreted this way.  So any string used as a pattern in one of these functions should either be passed through a filter to escape any special characters it contains, or (easier) redefine the  relevant parameter in the MOOSE API to be a Regular Expression (aka Pattern) rather than a literal.string.

**Comment by shadowze** [comment]
I avoid # or -  in any unit names I use _ instead

**Comment by thebgpikester** [comment]
GIven the issue is understood we dont have a commitment to change the way it works in code. I think the understanding contained above is enough. Archiving this.
