### ISSUE TITLE
only a idea

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1202]
i know we cant make request but only a small thing that was staying nice on A2G dispatcher.
on task control menu was nice to have a option to smoke the detected target.

tks and i hope you  think about my opinion ^^

**Comment by Delta-99** [comment]
Who says you can't make a request. There are a lot of requests for new features here and this is the right place to do it.

**Comment by Enfarda** [comment]
oh kk xD tks for info

**Comment by thebgpikester** [comment]
Needs a lot more design thought!

Smoking EVERY detected unit? really? So that would quickly kill the game. How does the Detecting aircraft know that other aircraft have detected it. Do they resmoke it or leave it after the 300seconds smoking? How do you reduce the smokes and prioritise only one or two vehicles to be smoked? WHat is the deciding mechanic?

Ciribob handled it by only smoking the lased unit but I dont see any way you could realistically approach this because you can't do a 1:1 smoking with multiple units.

I'm going to close this as no one is considering a workable design. The idea has to be fully presented before we could even hope to start work and there isnt any developers able to commit to more than bug fixes right now.

Please fully define the idea and consider all the issues and re-engage with some use cases when the author - @FlightControl-User comes back to DCS.
