### ISSUE TITLE
MaxSpawnAlive in :InitLimit ignored when :OnSpawnGroup used to assign newly spawned unit to CARGO_GROUP

### ISSUE THREAD

**Issue by AbortedMan** [FlightControl-Master/MOOSE#1221]
```
-- Here we setup the spawning of Infantry.
SpawnCargoInfantry = SPAWN
  :New( "Infantry" )
  :InitLimit( 20, 60 )
  :InitRandomizeZones( { ZONE_POLYGON:NewFromGroupName( "Pickup Location" ) } )
  :OnSpawnGroup(
    function( SpawnGroup )
      -- This will automatically add also the CargoInfantry object to the SetCargoInfantry (in the background through the event system).
      local CargoInfantry = CARGO_GROUP:New( SpawnGroup, "Infantry", SpawnGroup:GetName(), 150 )
    end
  )
  :SpawnScheduled( 1, 0.5 )
```
In this example from the Moose Example Missions (AID-CGO-250) InitLimit should stop the spawning of "Infantry" at 20, but this limit is ignored due to :OnSpawnGroup assigning CARGO_GROUP. MaxGroupSpawn in InitLimit is still functional and will stop spawning after 60 (in this case), but will spawn infinitely if set to 0 regardless of what MaxSpawnAlive is set to and regardless of these units alive alive.

This is reproduced on any instance of OnSpawnGroup being used to assign a CARGO_GROUP.

[AID-CGO-250 - Helicopter - Front-Line Enforcements.zip](https://github.com/FlightControl-Master/MOOSE/files/3762984/AID-CGO-250.-.Helicopter.-.Front-Line.Enforcements.zip)

**Comment by baluballa** [comment]
For me it seems :InitLimit( 20, 60 ) respect limit of groups, but not max alive units.

**Comment by thebgpikester** [comment]
Removed assignement to @FlightControl-User he is not available.
"For me it seems :InitLimit( 20, 60 ) respect limit of groups, but not max alive units."
You simply cannot use InitLimit with Cargo or any group that is destroyed and recreated because they are technically different groups, not the same. IniLimit() cannot cope with that scenario it's a lot more dumb. Closing the ticket, if I have misunderstood something, but in this very specific scenario, InitLimit() is working to monitor it's original Spawn and behaving as it was written.
