### ISSUE TITLE
Request for :GetSkill() function

### ISSUE THREAD

**Issue by RedMeKool** [FlightControl-Master/MOOSE#1237]
Would it be possible to add a function to retrieve a unit’s skill?

**Comment by funkyfranky** [comment]
No real DCS API function for this but you can get it from the unit's template
local myunit=UNIT:FindByName("unit name")
local skill=myunit:GetTemplate().skill

**Comment by RedMeKool** [comment]
Thank you, I didn’t know that.
But it won’t read anything set by InitSkill() right? Only the predefined mission templates?

Op 28 nov. 2019 om 22:55 heeft Frank <notifications@github.com> het volgende geschreven:

**Comment by thebgpikester** [comment]
It's unlikely that we will make new features to the core of moose due to the main developer no longer working on it. That's the honest truth. However, the skill is available as described above from the GetTemplate().skill, as long as the spawn hasnt changed the skill, which is done by completely recreating the entire template, not by changing something on an existing unit in the game. So if you use InitSkill(), you already know the skill and thus programmatically you have no requirement to ask for it again.
"But it won’t read anything set by InitSkill() right?" -- you set the skill, you know the skill, you have to track that yourself there.
