### ISSUE TITLE
AIRBASE.Nevada.Mellan_Airstrip does not exist

### ISSUE THREAD

**Issue by 132nd-Entropy** [FlightControl-Master/MOOSE#1263]
AIRBASE.Nevada.Mellan_Airstrip MOOSE documentation points towards AIRBASE.Nevada.Mellan_Airstrip, however, this seems not to exist. If one puts this into a table, the ATC_Ground script will break. Commenting it out will fix it. 

```ATC_Ground=ATC_GROUND_NEVADA:New(
  { --AIRBASE.Nevada.Creech_AFB,
    AIRBASE.Nevada.Groom_Lake_AFB,
    AIRBASE.Nevada.McCarran_International_Airport,
    AIRBASE.Nevada.Nellis_AFB,
    AIRBASE.Nevada.Beatty_Airport,
    AIRBASE.Nevada.Boulder_City_Airport,
    AIRBASE.Nevada.Echo_Bay,
    AIRBASE.Nevada.Henderson_Executive_Airport,
    AIRBASE.Nevada.Jean_Airport,
    AIRBASE.Nevada.Laughlin_Airport,
    AIRBASE.Nevada.Lincoln_County,
   -- AIRBASE.Nevada.Mellan_Airstrip,
    AIRBASE.Nevada.Mesquite,
    AIRBASE.Nevada.Mina_Airport_3Q0,
    AIRBASE.Nevada.North_Las_Vegas,
    AIRBASE.Nevada.Pahute_Mesa_Airstrip,
    AIRBASE.Nevada.Tonopah_Airport,
    AIRBASE.Nevada.Tonopah_Test_Range_Airfield
  }                                  
)  
:SetKickSpeedMiph(25)
:SetMaximumKickSpeedMiph(150)
:Start()

**Comment by thebgpikester** [comment]
Frank I've assigned you since this looks like we could change the code easily and @132nd-Entropy gave us the fix on a plate. There is background information in Discord channel #func-atc-ground .

Mellan doesnt exist as a usable airfield in DCS. I believe they were going to have it at some point and the code was likely in DCS somewhere. We need to see where it's in MOOSE and nuke it.

**Comment by funkyfranky** [comment]
Thanks, I'll check it!
