### ISSUE TITLE
Enhancement of AI_A2A_DISPATCHER

### ISSUE THREAD

**Issue by boagord** [FlightControl-Master/MOOSE#1308]
I would like to add a feature to AI_A2A_DISPATCHER and, in fact AI_AIR : 
For now SetDisengageRadius() works well but there is some limitation. Sometimes the SetDisengageRadius() cannot be set to match the SetBorderZone(). 

I.E : A Squadron based at Beslan and defending all the Russia / Georgia border  cannot have a proper SetDisengageRadius().

I thought about zones that when Defenders are outside those zones, the engagement is stopped and the CAP patrol is resumed.

**Comment by davidp57** [comment]
I'd really like that !

**Comment by Couby** [comment]
> I thought about zones that when Defenders **are inside** those zones, the engagement is stopped and the CAP patrol is resumed.

Hi, I think what you mean @boagord is when `Defenders **go outside** of those zones...`.

Sure this would be a nice improvement and better defense system behaviour. At this time it is easy to drag defenders and trap them outside of their CAP Area.

I think a nice implementation would be to add a **SetDisengageDistanceFromCapAreaLimits()** and/or **SetDisengageDistanceFromBorderInEnnemyLines()**.

**Comment by boagord** [comment]
> Hi, I think what you mean @boagord is when `Defenders **go outside** of those zones...`.

It depends on the logic used, It could be No Fly Zone as well as the allowed airspace.

**Comment by Salamandralex** [comment]
Very good idea !

**Comment by thebgpikester** [comment]
I don't really understand what the request is. Features to MOOSE are unlikely unless its Franks own work anyway, but I don't udnerstand what the feature should be anyway.

**Comment by Delta-99** [comment]
I think its just a ZONE rather than a radius which sounds a lot better to me.

This actually exists in AI_CAP_ZONE. I never migrated my stuff from AI_CAP_ZONE because it works well for me and I use ZONEs.

**Comment by Couby** [comment]
@Delta-99 
> This actually exists in AI_CAP_ZONE. I never migrated my stuff from AI_CAP_ZONE because it works well for me and I use ZONEs.

ZONEs in AI_CAP_ZONE, accordingly MOOSE documentation "define when the AI will engage with the detected airborne enemy targets (in that ZONE)."
![image](https://user-images.githubusercontent.com/4526037/80179708-6a04a500-8601-11ea-9b70-4d8d1607a175.png)

---

How do you set the **dis**engagement distance from your AI_CAP_ZONE ?
This in order to prevent your CAP to be dragged deep in enemy lines...

The sole disengagement setting we find is **SetDisengageRadius()**, but this setting is tied to homebase, for all aircrafts, which has sense when your CAP area is close to homebase, but not relevant :
- for "far" CAP area
- or when a squadron provide CAPs both for close AI_CAP_ZONE and far AI_CAP_ZONE.

**Comment by Couby** [comment]
The targeted behavior with a picture : 
![image](https://user-images.githubusercontent.com/4526037/80180996-42630c00-8604-11ea-839f-b3724c02de64.png)

**Comment by thebgpikester** [comment]
Everything is tied to Homebase, that's what a Squadron is, but if I spin this around, do you mean you want a Disengagement range per squadron, rather than a global setting on the Dispatcher, because different airbases on the same dispatcher have different ranges to the border?
The Global setting is fine if you don't put the border too close to an airbase, the Beslan example is a good example of how not to place your squadrons, it's unrealistic, better to focus on some code to stop spawning from Beslan if blue are too close. A Dispatcher MUST be setup with a distance from its extent of patrol to the border, that exceeds the max range of the longest range A2A weapon the other side has. If not, you can simply shoot them down without reacting. To use A2A_Dispatcher properly you should have quite decent buffer ranges between the border, the homebase, the patrol zone or the entire thing comes apart because of timing and DCS.
Disengaging happens, but like all code, it's run with timers that may not reflect what you instantly want and these are exploited because of the entire layer of the FSM and the way you have to switch Fighters off intelligently. It's just as easy to drag the bandits, and when they turn back, go after them, or go back to your orginal mission with a bit more time in hand. The entire class is vulnerable to "things that aren't perfect", this is one of them, but it's not the worst offender, the worst offender is the fact we have to resort to AI "on and off" to get DCS AI to do any holding back.
Also without a complete mission how do we know that the Disengage is even being honoured and it's not faulty? We had issues with it a year or so back. Anything is possible. I'd like to see an example mission where it's not working as it should (not hard ;)) and to have th ebehaviour put under the microsocope from there, in order to rule out a bug.

**Comment by thebgpikester** [comment]
Also that picture is not how it works. :)
DIsengage distance is measured from homebase, not patrol afaik.

**Comment by bigmillertime** [comment]
Good call on that picture not describing how it works. Can this be confirmed?

**Comment by Couby** [comment]
There are two pictures on this page at the moment : 
- one describing how it works (the first one)
- one describing the requested feature in this issue (the second one)

@thebgpikester the mission I'm working on : https://github.com/VEAF/735th_Training_AirDefense_Mission

Really easy to drag red flights out of area.

**Comment by Delta-99** [comment]
If you are using AI_CAP_ZONE then you can already do what you like. You can overlap the PATROL and ENGAGE zones and make it look exactly like your second picture. I'm pretty sure that is basically what I do.

They will disengage when outside the engage zone. Although at times I think I've seen them wonder outside a bit if they are in then thick of things. But that is probably just default AI behaviour that you will have a very hard time working around.

This is completely separate to AI_A2A_DISPATCHER I believe. I was just pointing out that functionality exists in Moose. Whether AI_A2A_DISPATCHER should use this or not is another question. I think there was a TON of input to AI_A2A_DISPATCHER when it was designed but I wasn't involved. Whether it works as it was designed, not sure!!

**Comment by funkyfranky** [comment]
Just to manage expectations. As the creator of this class is currently not active, new features are very unlikely to happen any time soon. This class is very complex. Therefore, for other people it is extremely difficult to add something new.

**Comment by Couby** [comment]
> You can overlap the PATROL and ENGAGE zones and make it look exactly like your second picture.

Will try :) .

> As the creator of this class is currently not active, new features are very unlikely to happen any time soon. This class is very complex. Therefore, for other people it is extremely difficult to add something new.

😭

**Comment by funkyfranky** [comment]
Yeah @Couby, I know :( But it is what it is. Sorry to be the bearer of bad news.

**Comment by thebgpikester** [comment]
I'll leave this ticket up for another week, but I can only reiterate the same things.
The really important thing to do with DIspatcher is to generate a lot of physical space between borders, patrol points and airbases, and cross check all the default configs that don't work. If you put a patrol out near a border it's asking for trouble, same with a border close to a patrol zone, the FSM will not react fast enough to avoid the stated circumstances. Yes, GCICAP/A2A_Dispatcher are massively limited, and so is DCS, it's taking manipulation of the AI to the nth level whilst only using basic finite states of "patrol and be dumb", "attack a specific target", "RTB". If the scenario is complex, stick to GCI only and dont have a patrol, this ensures a 1:1 scramble. Use runways with proven and tested taxiways, no backtracks, lots of parking space, your own cleanup scripts being aggressive.

Humbly, there is more chance of Dispatcher being replaced from the ground up, than being changed. It's good for what it is, in a specific scenario, in the stated config but it can fall apart easily without a good understanding of how it works.

**Comment by Delta-99** [comment]
I wonder if it is worthwhile to attempt to tell people to use the more simplified AI_CAP_ZONE? It works well and in fact I never moved on from it because AI_A2A_DISPATCHER was not developed yet and I saw no real need for me to attempt to migrate my stuff to using it cause what I developed worked as I wanted it to. I have a feeling that AI_CAP_ZONE will work for a lot of people unless they really want to get more involved and run into a lot more issues because of AI_A2A_DISPATCHER complexity.

AI_A2A_DISPATCHER was intended to make things easier I THINK and with more options etc but seems like it causes more trouble that it is really worth.

Perhaps rewriting it from the ground up is something Funky is interested in doing. It is sort of a fundamental thing that is needed in missions.

**Comment by thebgpikester** [comment]
Dispatcher is deeply embedded with people now, but for sure you can be smarter in using it, or not. I veer away from all the patrol classes for the simple fact that planes don't do that. They stay in one spot or go from A to B. GCI on the other hand is a part of it I coudlnt do without.

**Comment by Delta-99** [comment]
Very true that planes don't do that typically. My missions tend to be completely dynamic and not full-scale realistic either but more for fun and replayability. So having the enemy sort of pop-up randomly somewhere works for me and I think a lot of people for these types of missions.

As for a realistic CAP or PATROL I agree that this isn't a good method.
