### ISSUE TITLE
WW2 A/A Dispatcher sends aircraft in a random direction

### ISSUE THREAD

**Issue by Commiccannon** [FlightControl-Master/MOOSE#1738]
So i have been making a mission for ww2 stuff and found that the aircraft all like going into the top left corner of the map and only sometimes engage the enemy. This happens for both sides but not every single time but often enough to notice. I have attached the mission (Modified just to put the scripts in the mission instead of a assertload), a the script i am using, dcs log and a screenshot all in a .zip. Any help would be appreciated
[MOOSE Bug.zip](https://github.com/FlightControl-Master/MOOSE/files/9007432/MOOSE.Bug.zip)

**Comment by thebgpikester** [comment]
Hi @Commiccannon . Thank you for your report. I read through your log and looked at the code briefly and the picture. I don't have any suggestions for rectification. I am somewhat familiar with A2A_Dispatcher misbehaving like this. It's due to the constant behaviour correction of the script to the controller and we never located the root cause - this being several years ago now. Interestingly the script has not changed dramatically so expect this is on ED's side but we cannot confirm or deny, only confirm that there have been no major script changes in the last few years.

The author of A2A_Dispatcher left active development for MOOSE in 2018 and he is unable to assist directly. SInce then we have adopted new methods to control CAP's via teh OPS classes that FunkyFrranky began to write some years back. We find these are much more effective and since they have an active developer we have elected not to attempt to solve any similar A2A_Dispatcher issues and direct users to the free and currently supported methods instead.

I am sorry that you didn't get this to work and I am sorry I cannot recommend a solution to that class. Please come and join a Discord discussion on how to implement the OPS classes and a basic dispatcher if you need further assistance.
