### ISSUE TITLE
FlightGroup: Expected Speed 0 after WP1

### ISSUE THREAD

**Issue by Applevangelist** [FlightControl-Master/MOOSE#1862]
After reaching WP1 and Switching to WP2, the FG has an expected Speed of zero. This leads to planes hanging around on eg CAP Missions at <200kn IAS. Now, it might be the case that a speed of zero is **wanted** at this point but it's certainly not the rule. The problem seems to be that further down in OpsGroup, the  function
```
function OPSGROUP:GetExpectedSpeed()

  if self:IsHolding() or self:Is("Rearming") or self:IsWaiting() or self:IsRetreated() then
    return 0
  else
    return self.speedWp or 0
  end

end
```
is always returning zero as speed with case 1, where in more cases it should be returning self.speedWp. speedWP is only set once in OpsGroup in line 6341,10608 and 2280 in FlightGroup where for some reason it defaults to 
```
  if wp[2] then
    self.speedWp=wp[2].speed
  end
```

and OpsGroup 10609 is maybe not a good idea unless we're ground, helo and hovering, landing, taxiing I assume:

```
wp.speed=wp.speed or 0
```

**Comment by Applevangelist** [comment]
I still think a possible workaround would in FG 3718ff

```
  -- Speed in knots.
  Speed=Speed or self:GetSpeedCruise()
  
  local mission = self:GetMissionCurrent()
  if mission and not self.isHelo then
    Speed = mission.missionSpeed and mission.missionSpeed or self:GetSpeedCruise()
  end
  ```` 

this time with checking if the mission exists.

**Comment by funkyfranky** [comment]
The "expected" speed is more of an informative nature. It is mostly used to check if ground units are stuck (expected speed > 0 and actual speed=0). It might not even be correct under all circumstances (because there are too many ways a unit is routed). So if the expected speed says 0 it does not necessarily mean the waypoint speed is 0.

The workaround is an option, yes, but it should not be necessary. When the waypoint for a mission is created, the mission speed is already passed as a parameter (see OPSGROUP:RouteToMission() function). The real question is, is the speed too low when this waypoint is created and then fix that.

Did you print out what the speed is in FG 3718ff? Is it really too low?

**Comment by Applevangelist** [comment]
Jup - below 200kn for most units, defo far away from the expected 250kn plus altitude adjustment

**Comment by Applevangelist** [comment]
[FG Slow CAP Demos.zip](https://github.com/FlightControl-Master/MOOSE/files/10329143/FG.Slow.CAP.Demos.zip)

**Comment by Applevangelist** [comment]
Two demos. One with the Moose from 2 days ago. The speed to the CAP station is random at best, older models like the F1BE have problems to climb to stations > 15k ft. Hardly anone crusing at 350kn IAS (mission speed).
Patched version (with my suggested patch) - planes seem to go to station at CruiseSpeed (0.7*max), reach their station and do a lofty 350+ kn on station, all around

**Comment by funkyfranky** [comment]
Thanks, I did not check yet but already this line 
`mission.missionSpeed = UTILS.KnotsToAltKIAS(Speed or 350, Altitude)`
in AUFTRAG:NewCAP() looks suspiciously wrong as misssionSpeed should be in km/h. If given in knots, it will be too slow.

**Comment by Applevangelist** [comment]
Maybe but that wasn’t in the 29 dec version

**Comment by Applevangelist** [comment]
Forbid Afterburner is the culprit
