### ISSUE TITLE
AI_PATROL, AI_CAP, AI_CAS: altitude from ground level

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#217]
Add option for radio (ground) altitude hold preventing planes crashing into the ground on hilly terrain.

The min and max range in meters is then calculated from the ground instead on sea level.

**Comment by Delta-99** [comment]
In /Moose/Utilities/Routines.lua you are actually using "RADIO" altitude type as a parameter option for building waypoints for helicopters.

I suppose we can use the same in AI_PATROL, AI_CAP and AI_CAS when creating the zone. Perhaps have a property with "RADIO" as the default. If parameter passed in can change the property. I like how you did the one above too so that it accepts "RADIO" or "AGL", "BARO" or "ASL". I would prefer to use AGL and ASL as they mean more to me than RADIO and BARO and match ME terminology as well.

**Comment by Delta-99** [comment]
Just created a PULL Request with these changes

**Comment by JG7XMan** [comment]
This is simply fantastic! Has this been implemented yet or still discussion phase?

**Comment by Delta-99** [comment]
I developed it and it is working great in my branch. Just waiting for FC to incorporate into his branch and available to everyone.

NOTE, this doesn't completely prevent planes from crashing into the mountains but it does help tremendously. I see them still crashing but on a much lesser degree. And it mostly is planes that are flying too slow that try to pull up to late to climb over a peak.

It also allows you to have patrols hiding around in the valleys much easier. What it does stop is waypoints being generated in a mountain which AI probably will try and fly directly to!!

**Comment by FlightControl-Master** [comment]
Change accepted.

**Comment by FlightControl-Master** [comment]
Ill explain you when I am back, how to make a new Moose.lua files from the detailed moose files.

**Comment by Delta-99** [comment]
I did update the main Moose.lua. I found the .bat script and ran it. Except I didn't exactly know what parameter 3 was for so I just updated the main moose.lua file. I think the 3rd parameter is for putting moose.lua somewhere else as well.

But yes some instructions when you are back would be useful.

**Comment by FlightControl-Master** [comment]
Cool. I know the batch file stuff is not fancy, but it works and it provides some retro feeling into the ms-dos times :-) well pick this up when back. Thanks for your efforts.
