### ISSUE TITLE
Something between Feb 3 - Feb 8 release causing error thrown in log file and planes not taking off anymore

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#239]
The following was post in slack and you can see the comments via this link: https://flightcontrol.slack.com/archives/general/p1486936780002281

copied here:

> something in the changes between Feb 3rd and Feb 8th inclusive has broken Respawning in some situations. The Feb 2nd Moose.lua does not have this problem. The Feb 8th Moose.lua does have this problem. This is stuff that has been working for a while and all of a sudden not with no changes. Happens in a situation with AI_CAP or AI_CAS when planes RTB. After RTB they will not take off again OR will take off one more time then land and not take off again. This happens both with using AI_BALANCER and without. I get this error message in the log file:

Not easy to copy / paste from slack so just posting the links.

Log file error output is here: https://flightcontrol.slack.com/files/delta99/F43MK05PA/-.txt

Also from Slack:

> Note the AIB-007 I just created was using Moose version from Feb 2nd so it works fine and no errors in logfile.
> 
> Sigh, about 2 hours wasted debugging that because I thought it was something I was causing by calling an __RTB(1) on a patrol zone. After reverting moose.lua back to Feb 2nd no errors and my __RTB's working perfectly fine again. Something broken it looks like in ReSpawnFunction(Respawn) it looke like. No errors thrown in Feb 2nd version.
> 
> After more debugging this is the last version hash that works: ab345f5ad2de5761d7acd406d0ed07e4095350f9 - you can check your changes after that.

I was heading down the road of looking at the changes with uncontrolled because that is the closest I could find that might be messing with spawning / red-awning of aircraft. The error happens when a plane is attempted to be respawned via AI_BALANCER and other situations.

**Comment by FlightControl-Master** [comment]
This is the code that fails:

``` lua
  function FSM:_delayed_transition( EventName )
    return function( self, DelaySeconds, ... )
      self:T2( "Delayed Event: " .. EventName )
      local CallID = 0
      if DelaySeconds < 0 then -- Only call the event ONCE!
        DelaySeconds = math.abs( DelaySeconds )
        if not self._EventSchedules[EventName] then
          CallID = self.CallScheduler:Schedule( self, self._handler, { EventName, ... }, DelaySeconds or 1 )
          self._EventSchedules[EventName] = CallID
        else
          -- reschedule
        end
      else
        CallID = self.CallScheduler:Schedule( self, self._handler, { EventName, ... }, DelaySeconds or 1 )
      end
      self:T2( { CallID = CallID } )
    end
  end
```

**Comment by FlightControl-Master** [comment]
The line `if DelaySeconds < 0 then`
is where the error is reported.

Question @Delta-99 : When you call _RTB, do you specify a DelaySeconds parameter?
You can trigger events in two ways: Asynchronously and Synchronously.
Asynchronously, the syntax is: self:__Event( DelaySeconds )
Synchronously, the syntax is: self:Event()

pls check.

Anyway, I am going to ensure that a DelaySeconds in given in an asynchronous call, otherwise i'll log an error message and the processing will stop.

**Comment by FlightControl-Master** [comment]
The reason why "suddenly" this error pops up, is because it was an absolutely necessary change.
Now, in an asynchronous event trigger, one can also provide a **negative** DelaySeconds parameter.
The difference between an positive and a negative DelaySeconds parameter is:
- With positive DelaySeconds the event will be triggered, regardless if it was triggered before. This can result in many event triggers of the same event.
- With negative DelaySeconds the event will be triggered *ONLY ONE TIME*, regardless if it was triggered before. This can only result in *ONE* event triggered of the same event until it was processed.

So, i am testing for the DelaySeconds, to understand what needs to be done.

FC

**Comment by Delta-99** [comment]
In my limited testing this looks fixed in this revision - https://github.com/FlightControl-Master/MOOSE/commit/748e5cc8f843d3c95802783a338850ff48c00149

I just quickly tested AI_BALANCER and planes took off again after landing (which was broken by this). Also, if I use a radio command to that triggers a __RTB(1) the error in the log is NOT shown and those planes I can get to patrol again.

Good work FC. I would close this issue.
