### ISSUE TITLE
SPAWNSTATIC: Spawn static objects

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#327]
If you attempt to spawn a static, SPAWN doesn't find the template name and cannot spawn or respawn a static object.

Whilst it might seem out of scope, statics have unique objects not accessible as a unit such as a factory or other buildings and placing these with randomisation or respawning them would be useful and seems normal to most users.

MIST currently can do this for all statics bar FARPS and warehouses.

**Comment by thebgpikester** [comment]
closed in error - believed spawnfromstatic was the method, but its not.

**Comment by FlightControl-Master** [comment]
I understand and will add this. It is highly needed. Can you label your requests? (Use the labels on the right). What method would you like to see?

**Comment by thebgpikester** [comment]
OK, so you can't late activate statics so it has to be "moved" So i think 

- clone static to zone, (duplicates the static inside a named trigger zone)
- move static to zone (moves static to a zone by deleting the old one) 
- Clone static to VEC3
- Move static to VEC3
- Respawn static inside zone (once dead it respawns nearby - how to handle destroyed cleanup? can we prevent respawning ontop of itself?)
- Respawn Static to VEC3 (once dead spawns at specific position)

Function should contain options for, scheduler to do this at timed speed. Should also tie to scoring which hasn't been done yet.

Something like: 
CloneStaticZ(staticname,zonename)
MoveStaticV(staticname,vec3)
RespawnStatic(staticname,zonename, delayseconds)
RespawnStatic(staticname,vec3, delayseconds)
thoughts?

**Comment by FlightControl-Master** [comment]
would it make sense to make a SPAWNSTATIC class, because it is an object of its own

**Comment by thebgpikester** [comment]
I can't answer that I am afraid, the design is better handled by yourself! Marking as a bug since its a fairly core requirement. Not sure of the status as  I believe may be "ready for testing"?

**Comment by Grey-Echo** [comment]
I'm making it an enhancement back, since it is essentially what it is, but I assigned it to the Moose-2.0 milestone, since it is a critical feature.

**Comment by FlightControl-Master** [comment]
Question, if I deliver SPAWNSTATIC, would we end up with wanting the same kind of Spawn functions as in SPAWN? I mean... if i create a new class, it might be that i need to create a SPAWN_BASE class, and then make specializations SPAWN and SPAWNSTATIC... It is a lot more work than one would think..

**Comment by Grey-Echo** [comment]
If there is at least one method in common between SPAWN and the future SPAWNSTATIC, then it makes sense to make them inherit SPAWN_BASE. Otherwise, there is no need to.

When I look at @thebgpikester  method propositions, I don't see any overlap with the current SPAWN. So I think it is fine making a separate SPAWNSTATIC class. I might be overlooking something though.

**Comment by FlightControl-Master** [comment]
You will see it quickly coming... Can we spawn scheduled? Can we randomize in zones? Can we spawn in an array? Can it Respawn. Suggest we do a good requirement discussion, because i want a good design from day one.

**Comment by FlightControl-Master** [comment]
In terms of spawning for statics, would it be okay if i make a SPAWNSTATIC, with a simple API to start with. Just a SPAWNSTATIC that allows to SPAWN a static with "Template" defined within the ME or with the direct type name, so that you can spawn a static at an x,y coordinate. But without randomization, scheduled, array etc. Later in release 2.1, i can then rework that further and add features?

I could make something like this:

```lua
HouseStatic = SPAWNSTATIC:New( "HouseTemplate" )
HouseStatic:SpawnFromPointVec2( ZONE:New( "ZoneName" ):GetRandomPointtVec2() )
HouseStatic:SpawnFromVec2( ZONE:New( "ZoneName" ):GetRandomVec2() )
```

**The functionality in the first version for 2.0 would contain:**
1. Create a SPAWNSTATIC object from a string containing the name of the static, and the type name of the static.
2. Create a SPAWNSTATIC object from a string containing a name of an existing STATIC, that is copied.
3. Spawn a static at a Vec2 = { x = , y = } coordinate.
4. Spawn a static at a PointVec2 = POINT_VEC2 object having a X, Y coordinate.

**Remarks;**
1. Statics are spawned at land height.
2. There is no respawn.
3. There is no transpose.
4. There is no internal array in SPAWNSTATIC. Statics are spawned on the fly.

please review and comment.

**Comment by thebgpikester** [comment]
Seems OK, just a thought, how do we approach the problem of no late activation for them? Do we ever want to use a normal unit as a template or just leave the VEC2 as the placement method? Ease of use is both ... "meh".... in case one you need to obtain the vec2, perhaps with a late activated unit anyway.

**Comment by Grey-Echo** [comment]
This is a reasonably huge issue, and the solution needs a bit of time to be designed properly. I am therefore postponing it to Moose-2.1 .

**Comment by FlightControl-Master** [comment]
This development has started in branch master-eng-327-spawnstatic.

**Comment by thebgpikester** [comment]
Good luck. Probably useful to mention that warehouse and FARP classes can't be moved whislt keepign their logic as far as anyone in the development of DCS scripting has ever managed. You might know this already.

Can I also point out, it might be good to have a check on the validity of the terrain before placement? Because you can spawn them into the sea easily, you can put them too close to other houses and terrain features. also i think AIrbases have a check or somehting in DCS for valid ground

**Comment by FlightControl-Master** [comment]
I have a first prototype working. You can test this if you go to branch master-enh-327-spawnstatic on the MOOSE and the MOOSE_MISSIONS repositories. You'll need to change branches on both repositories in github desktop. Press SYNC. Then go to LDT, and press F5 both on the Moose_Framework and the Moose_Missions projects.

You'll see the following:

1. a new file SpawnStatic.lua has been added in Moose Development/Core in the MOOSE repository.
2. a new folder structure under SPS - Spawning Statics has been created in the MOOSE_MISSIONS repository.

Try the new mission SPS-100 in the MOOSE_MISSIONS repository. Open the SPS-100 - Simple Spawning.lua and check the code (I listed it here):

```lua
local ZonePosition = ZONE:New( "Position" )

local SpawnBuilding = SPAWNSTATIC:NewFromStatic( "Building", country.id.GERMANY )
local SpawnBarrack = SPAWNSTATIC:NewFromStatic( "Barrack", country.id.GERMANY )

local ZonePointVec2 = ZonePosition:GetPointVec2()

local Building = SpawnBuilding:SpawnFromZone( ZonePosition, 0 )

for Heading = 0, 360,60 do
  local Radial = Heading * ( math.pi*2 ) / 360
  local x = ZonePointVec2:GetLat() + math.cos( Radial ) * 150
  local y = ZonePointVec2:GetLon() + math.sin( Radial ) * 150
  SpawnBarrack:SpawnFromPointVec2( POINT_VEC2:New( x, y ), Heading + 90 )
end
```

What this code does is:

1. It identifies the Zone where to do the spawning.
2. It creates two SPAWNSTATIC objects, one for a building and one for barracks.
3. A building is created in the center of the Zone.
4. Barracks are created around the center of the Zone.

A couple of points to consider now:
* For simplicity, I think it is the best to have one SPAWNSTATIC object per Static you want to spawn. Is this ok?
* The only SPAWNSTATIC constructor working at this moment is NewFromStatic. The other planned constructor is NewFromType, but this will need more work to make.
* Two Spawn methods are created: SpawnFromPointVec2 and SpawnFromZone. Is this sufficient???
* There won't be any Init methods... Is this ok???
* There won't be any Respawn methods... Is this ok???
* What other Spawn APIs would you like to see...
* The naming of the created statics is the _TemplateName_#_nnnnn_, where nnnnn is the index of the stataic spawned. In the Spawn methods, you can give optionally a new name of the Static, overriding the template name.
* There is a question on Country. Each Static has a country. I can set it for default at the constructor, and then allow to give a override CountryID when Spawning (not my preference though, because then you'll get two optional parameters in the Spawn methods, one for the new name, and one for the country => confusing ).

* I see Pikey is looking for an additional check of the ground. To be honest, not so easy to implement and also, what is the value if the MD defines a wrong position??? 

pls test and consider the questions...

**Comment by FlightControl-Master** [comment]
OK. Nothing was tested or no feedback?. I am moving this to master...
