### ISSUE TITLE
CONTROLLABLE.TaskReturnToBase

### ISSUE THREAD

**Issue by EasyEB** [FlightControl-Master/MOOSE#337]
Documentation of how to implement is missing, or this feature is not functional.

**Comment by FlightControl-Master** [comment]
We need a function in CONTROLLABLE to route to an AIRBASE. If possible the CONTROLLER can register the home base when tasking off from that base. So the method could become :RTB() with an optional parameter an AIRBASE object. If not given, the CONTROLLABLE will fly to the home made if known or to the nearest if spawned mid-air.

**Comment by Delta-99** [comment]
BTW, I beleive there is a documentation stub for this method. I searched source and couldn't find it. I suspect you planned on doing this in the past and the documentiion is still there.

My workaround for this at the moment is to use CopyRoute of a ME placed template group that has a land waypoint set. Seems to work really well.

**Comment by FlightControl-Master** [comment]
There is indeed an old attempt of mine in the code. I know now how to do it and can work the code :-) jippie! (This method is _really_ old...). Time to improve it :-) @EasyEB @Delta-99

**Comment by FlightControl-Master** [comment]
-- A new method has been defined: GROUP:RouteRTB( AIRBASE, Speed )
-- Documentation has been updated.
-- The method respawns the air group and sets the route to the target airbase. The method has immediate effect, the air group will RTB to the defined AIRBASE object.
-- Please read the documentation, because there are some side effects to this new method.
-- Test mission GRP-400 has been defined. Please test! @EasyEB

**Comment by Grey-Echo** [comment]
I tested GRP-400 and although everything works as stated in the lua file of the mission, some weird thing happened

- When the `RouteRTB()` is called  each UNIT generate an "S_EVENT_CRASH" is it intended ?
- Might be unrelated, but i have the following error in dcs.log (available here : https://gist.github.com/Grey-Echo/89c3c1ea79723568a1e978daf9123bf2) : 

`00441.362 INFO    SCRIPTING: Error in timer function: [string "Scripts/Moose/Wrapper/Unit.lua"]:113: attempt to index local 'DCSUnit' (a nil value)`

**Comment by Delta-99** [comment]
@FlightControl-Master I don't understand why you would have to respawn the group in order to RTB. Can't you just use similar logic as any of the AI processes when they got to RTB state? Or use a Route() to replace there route with a land waypoint? I'm doing this now with a CopyRoute but I'm sure can be done straight away.

**Comment by FlightControl-Master** [comment]
Respawning was my last option. Maybe i am wrong and happy to learn.
Let me explain why respawning was my last option.

The RouteRTB() method defines a route from and a route to point. That was given to a mission task.
When the route to point contains exactly the landing actions and coordinates of the airbase, the plane would fly to the airbase, but would not land. It would fly past it, and then fly to the last waypoint defined in the mission editor and land there... In other words, of the group has a land action in its route this would be considered the home base and any route you set to land the plane at another base, there plane won't land but will fly afterwards to its home base.

@Delta-99 How do you make the plane land at an airbase of choice when the plane is airborne? 
Happy to ditch the Respawn! It is a pain.

**Comment by Delta-99** [comment]
I see your problem now. Let me test something forcing a landing at a different airbase than the starting one. If it can be done by ME and works with your CopyRoute then you can probably do it via scripting.

**Comment by Delta-99** [comment]
My idea did NOT work. It seems, like FC has found out, that the starting airport is coded somehow into DCS so even if you give them a land waypoint at another airbase (at least through my method) they go to the airport, do some strange moves and then head back to their starting airport. I even had an E-3A once try to climb 90 degrees straight up. Loose power and then dropped to the ground on his tail!!! LOL. It was fun to watch.

So I wonder if there is something in the DCS Unit properties that signify the "starting" airport. If so, maybe FC can modify that and things will work. If not, then looks like this respawn thing may be the only way to get it to work.

**Comment by FlightControl-Master** [comment]
ready

**Comment by Delta-99** [comment]
Did you find something that made this work like the starting airfield in the Unit properties. I am pretty sure I've seen that somewhere.

Or you gave up and going with this implementation?

If you are going with this implementation there should be very large warning signs on the function and documentation somewhere that this is what happens when this is used because it will likely break a lot of missions or cause unexpected behaviour for mission designers.
