### ISSUE TITLE
Bombers not responding to CAS function

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#344]
Aircraft of type Bomber will not follow parameters set by CAS function type . Review supplied videos for detail in CAS section.

**Comment by thebgpikester** [comment]
xref https://flightcontrol.slack.com/archives/C3R68L561/p1490441593981287
Question: Can aircraft that have non native taskings be forced to make them? Ie Bombers perform CAS, A-10C perform CAP etc. Or are their finer rules for this. Answering this question will allow us to define as bug or not.

**Comment by Delta-99** [comment]
I beleive so or at least I think I read this in the hoggit wiki with regards to setting tasks and enroute tasks via scripting. I think they said when these items are selected in the editor it is simply a way to help the user select the right aircraft for the job. But technically any aircraft can do CAS for instance. If I come across that in the wiki again I will put a link here.

**Comment by thebgpikester** [comment]
I guess the next step is to create a simple mission that has a known "bomber" that cannot natively do CAS and make it do it, in the simplest way possible. I don't know how to do that, any ideas?

**Comment by FlightControl-Master** [comment]
We need a new AI_BOMB class

**Comment by Delta-99** [comment]
Create one in the mission editor with a plane that is known to work. Then spawn your bomber with Moose and use CopyRoute. That is first pass. See what happens. If it doesn't perform as expected then look at calling some of the EnrouteTask type methods.

**Comment by gunterlund** [comment]
Need more information on how to use Copyroute. I see the following parameters
CONTROLLABLE:CopyRoute(Begin, End, Randomize, Radius)

I dont see how you tie this to the aircraft to copy. Is there a test mission to review?

**Comment by Delta-99** [comment]
@gunterlund here is a sample directly from my mission:

`  USAWACSPatrolGroup = SPAWN:New("US AI AWACS 1"):InitRepeatOnEngineShutDown():Spawn()
  local tempRoute = GROUP:FindByName("US AI AWACS Route 1"):CopyRoute(0, 0, true, 100)
  USAWACSPatrolGroup:Route(tempRoute)`

**US AI AWACS 1** is a group defined in ME that I want to be "programmed" by Moose obviously. Its just sitting on an airport with no waypoints. This would be your bomber.

**US AI AWACS Route 1** is a group defined in the ME that I just want to use for the waypoints. This would be a plane that can do CAS so that you can setup waypoints and actions just for testing purposes. In my mission for the AWACS I have waypoints including an orbit in racetrack pattern between waypoint 2 and 3. This gets copied via the CopyRoute to my Moose spawned plane with the above commands. Note, it has 4 waypoints where like I said on waypoint 2 has the orbit setup on it. Basically the first parameter to copyroute is the index of the first waypoint to copy (0 indexed or waypoint 0). The 2nd parameter is the index **from** the last waypoint. So 0 really means to copy to waypoint 4. Lets say we used CopyRoute(1,1,...) then it would copy waypoints 1-3 in this case. 3rd parameter allows a little bit of randomization of the actual waypoint with a radius at that point.

**Comment by Delta-99** [comment]
From the hoggit wiki and [link here](http://wiki.hoggit.us/view/DCS_task_engageTargets):

> Within the mission editor the task role selection filters the list of valid attributeNames to be relevant to this task. In reality that doesn't matter and you can assign whatever attribute you want for an aircraft to attack. 

This is why I said above I believe via scripting you can use a bomber (or any plane) to do CAS. This statement seems to imply that.

**Comment by gunterlund** [comment]
Delta not sure how this will show our problem as you can  make cas missions in the editor using a bomber and they function.

**Comment by Delta-99** [comment]
Oh, I thought you couldn't do that. In any event then maybe CAS as implemented in Moose should follow this type of method instead of attempting to more finely control units. I know FC has a higher level thinking going on here especially with regards to detecting units and such but perhaps it's too much. Maybe simplify and make it work like it would if defined in the editor. Because there it works well from what I have seen. I think the best would be to use an enroute task with the option of search in radius or whatever it is. I've seen this work extremely well in the editor.

**Comment by gunterlund** [comment]
example? Are you talking about a moose function or an ME function?

**Comment by Delta-99** [comment]
Not sure what example you are looking for or what part of my answer you are referring to

**Comment by gunterlund** [comment]
I think the best would be to use an enroute task with the option of search in radius or whatever it is. I've seen this work extremely well in the editor.

**Comment by Delta-99** [comment]
It's an ME function. Easily reproduced in Moose. If I remember I can out an example mission up. Super simple.

**Comment by FlightControl-Master** [comment]
@gunterlund its all yours!
bombing is implemented, but i can't get it to work properly, bombs seem to explode just after the release. Can you check this a bit please too?
