### ISSUE TITLE
Replace all spaces in directory/filename paths with underscores

### ISSUE THREAD

**Issue by glyphoglossus** [FlightControl-Master/MOOSE#35]
This is probably not a big deal for most developers/users, but if anyone is working with the files remotes, or even need to transfer the files, many transfer protocols and programs (scp, rsync) find spaces a major problem, especially when over multiple file systems (e.g., Linux/OSX to Windows and back, which is my case). There are many work-arounds, from quoting to escaping, but as I have discovered when developing on my primary system (Linux) and pushing updates to a Windows deployment system, these are fragile and, worse, vary depending on protocol and tools. I think if the spaces are not strictly necessary, underscores or hyphens would make for a much more robust code base.

**Comment by FlightControl-Master** [comment]
So, you suggest to replace ALL files in the MOOSE system with underscores?
I don't understand why you are developing on a linux system, as DCS is windows based.
Note that a good development environment for MOOSE is Eclipse. And there is a specific reason for that: it contains intellisense documentation functionality for lua code, by using @tags in the code...

**Comment by jeetsukumaran** [comment]
Hi FCM,

I understand if you find this objectionable, and reject this request!

Yes, DCS is windows based. But that does not mean that code development needs to be restricted there, especially since Lua is cross-platform. My workflow is develop in a environment that I am happy with, and then "publish"/deploy to execution environment. I have a very good (general) development environment in my Linux world, which includes lots of tools: find, grep, awk, sed, etc. 

But even in the Windows world, the moment you stop relying on the GUI and use e.g, shell/Powershell/cygwin or the upcoming WSL, spaces in file names and paths becomes tricky when using tools such as rsync, awk, etc.

So, my suggestion is that yes, for maximum reliability (even within Windows, it is a good idea to avoid spaces in any paths). But this is your choice!

**Comment by glyphoglossus** [comment]
p.s., above is me from my primary account!

**Comment by FlightControl-Master** [comment]
okay, i'll take it into consideration, thanks. Maybe when i have time i will do this change. Note that i'll need to change ALL source files, so a bit tricky job...

**Comment by glyphoglossus** [comment]
If you have cygwin or a Linux dev environment:

    find /tmp/ -depth -name "* *" -execdir rename 's/ /_/g' "{}" \;

But I am sure there are Windows utilities that do the same.

Then you can tell git

   git add -Av .

**Comment by FlightControl-Master** [comment]
okay, i'll check it

**Comment by FlightControl-Master** [comment]
So, Jeet, you want me to rename every file within Moose to an underscore, right?

**Comment by glyphoglossus** [comment]
Only if you agree that it would be helpful. For 99% of users/developers 
here, it probably makes no difference! :)

**Comment by FlightControl-Master** [comment]
OK, let me have a look at this... so only filenames, right?

**Comment by FlightControl-Master** [comment]
Not needed. DCS is windows.
