### ISSUE TITLE
Some methods in GROUP are inherited from POSITIONNABLE, but aren't compatible with GROUPs

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#362]
The DCS method Object:getPosition() doesn't work on Group. It is used in 6 methods in POSITIONNABLE:
- GetPointVec2()
- GetRandomVec3()
- GetVec3()
- GetVec2()
- GetHeading()
- GetPositionVec3()

Only 3 of them are polymorphic in GROUP to make them compatible:
- GetVec3()
- GetVec2()
- GetPositionVec3()

Which means that a call to GROUP:GetPointVec2(), GROUP:GetRandomVec3() or GROUP:GetHeading() will result in an error.

**Fix I'm working on:**
Make those 3 methods polymorphic in GROUP, by returning the first UNIT of the GROUP's GetPointVec2() and GetRandomVec3(), and by returning the mean of the GetHeading of each UNITs of the GROUP

**Comment by FlightControl-Master** [comment]
Excellent! This is the way! You see, group is an isolated entity within the dcs hierarchy. But it is controllable. That's how i got to this class hierarchy, the CONTROLLABLE objects must be "POSITIONABLE". But since group does not natively implement these functions, i thought of implementing them in a polymorphic fashion.... Just didn't get there yet for ask these functions. I did implement there ones i needed, but not all. Same is with UNIT and GROUP.

**Comment by Grey-Echo** [comment]
I'm closing this issue, but I opened issue #365 to solve this issue for the larger picture.
