### ISSUE TITLE
AI_CARGO_TROOPS: Cargo unload when vehicle is at a stop

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#378]
Need to have the ability to have Cargo automatically unload when vehicle comes to a stop. Likewise have Cargo Load if vehicle starts to move.
This process simulates APC's disembarking troops in a battle zone. This would be similar to Mbot's Dismount Lua Script but put it in a MOOSE environment. Since MOOSE deals with pre-defined groups as cargo this would also account for casualties in the group which Mbot's lua cannot do.

**Comment by Grey-Echo** [comment]
Interesting. I think @FlightControl-Master is doing some work on cargo as part of issue #353 . That might be related.

**Comment by FlightControl-User** [comment]
Make AI_CARGO_DISPATCHER...

**Comment by gunterlund** [comment]
holy crap did this get done. What is the demo mission

**Comment by gunterlund** [comment]
Wait a minute 2.4!!! Arghhh!!

**Comment by FlightControl-User** [comment]
Which is next week...

**Comment by FlightControl-User** [comment]
@gunterlund 
The development has started on this item.
Find the first protype mission here:
https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/develop/AIC%20-%20AI%20Cargo/TRP%20-%20Troops/AIC-TRP-000%20-%20Troops

Let me know what you think of this implementation... 👍

**Comment by gunterlund** [comment]
Looking at this requirement, 378 is still current. Extending on this concept. 
Need to have a class which allows a cargo and carrier to be linked. Mission AIC laid the foundation using the parameter CargoTroops = AI_CARGO_TROOPS:New( CargoCarrier, InfantryCargo, 1500). 
Concept
1. When a vehicle is stopped, the cargo will deploy on a side of the vehicle designated by the mission designer. for instance embark 5 meters to the rear, or 10 meters to the front.
2. When the carrier is designated to move again via user intervention as a controllable vehicle,  or waypoints, the cargo will first load into the carrier before proceeding. 
3. The parameters for this class will include designation of the linked cargo to a linked carrier.  
4. A parameter will be set on how close the carrier can come to enemy contact before the carrier stops and the cargo is deployed. Once in contact, the carrier will halt and deploy the cargo. Once enemy is no longer in contact the Cargo will embark and the carrier will proceed. If no cargo exist or is present the carrier can move freely.  
5. If the carrier is destroyed while the cargo is deployed, the cargo can be reassigned to another carrier through the MOOSE framework. 
6. Through the MOOSE framework, the cargo can be commanded to embark  or disembark the carrier.
7. Multiple classes can be designated as cargo including Manpads, mortars, AAA guns, 
8. The cargo and carrier can be "unlinked" via scripting.

**Comment by FlightControl-User** [comment]
@gunterlund working on it :-)

**Comment by FlightControl-User** [comment]
@gunterlund point __5. If the carrier is destroyed while the cargo is deployed, the cargo can be reassigned to another carrier through the MOOSE framework.__

I will implement this by adding a method :SetCargoCarrier(), which will allow to "switch" carriers.
When the troops are boarded, I will unboard them and they will run to the new carrier and board there.

Would it make sense to board to a **nearest** "free" carrier? I could make a function that helps finding that carrier unit... There is one catch though... That means that I will need to put a flag at the carrier group that troops are contained or not. which makes sense actually... So I could implement a scan around the troops searching for a nearest carrier within a range.
If there is a carrier found, and it is free, I will allow to board into that carrier.
This process could be implemented using 2 methods as part of the AI_CARGO_TROOPS. An event handler will be triggered when the carrier is destroyed. In the event handler, one can search for a free carrier within range. If found, assign the troops to the new carrier. Otherwise the process will stop.
example:

```lua
local InfantryGroup = GROUP:FindByName( "Infantry" )
local InfantryCargo = CARGO_GROUP:New( InfantryGroup, "Engineers", "Infantry Engineers", 2000 )
local CargoCarrier = UNIT:FindByName( "Carrier" )
CargoTroops = AI_CARGO_TROOPS:New( CargoCarrier, InfantryCargo, 500 )

function CargoTroops:OnAfterCarrierDestroyed( Coordinate )
  -- The coordinate is passed where the carrier is destroyed.
  local NewCarrier = self:FindCarrier( Coordinate, Range ) which returns one Carrier GROUP object or nil.
  if NewCarrier then
    self:SetCarrier( NewCarrier )
  end
end 
```

**Comment by FlightControl-User** [comment]
I will also add a routine that when the APC is hit, the troops will unboard.

**Comment by FlightControl-User** [comment]
@gunterlund cannot fix point #2 
__2. When the carrier is designated to move again via user intervention as a controllable vehicle, or waypoints, the cargo will first load into the carrier before proceeding.__

I've done a bug report to ED...

https://forums.eagle.ru/showthread.php?t=205923

**Comment by FlightControl-User** [comment]
_7. Multiple classes can be designated as cargo including Manpads, mortars, AAA guns,_

I've done my best to make this work. But mortars and stringer comm can't move (they are stuck), so i let them dissapear when boarding, they won't run. When these unload, they will be spawned around the carrier.

**Comment by FlightControl-User** [comment]
done.
