### ISSUE TITLE
Better version stamp for Moose dynamic and static creation

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#461]
Is it possible to pickup the GIT version when creating a Moose Dynamic or Static version?

The timestamp used to be useful in the past when there was a static version created before this new development process because a static Moose version was created anytime FC committed a version and it was easy to find the Moose version that was used.

However, now a timestamp isn't much useful because of mostly using a Dynamic version. However, if the process for creating the dynamic version (and static too) used the GIT version then it would be very easy to get back to that version for testing.

How did this come up? Well, I created a mission for @thebgpikester and forgot to change it to static when I sent him the .miz file. Now of course this mission did NOT behave the same for him at all. This is most likely because we are using different Moose versions. This is sort of my fault for not creating a static moose version of this mission BUT also points out that its very difficult for us to figure out what Moose versions we are both working with. With my system completely fried for the past week and @thebgpikester not exactly sure what version he is working with its impossible for him to properly test this or use it at all.

This exact scenario is why I was pushing for static moose versions to be created like before. Dynamic is great for testing but for any type of situation like this, it makes things way more difficult.

**Comment by Grey-Echo** [comment]
> Dynamic is great for testing but for any type of situation like this, it makes things way more difficult.

Exactly. If you want to create a mission, you should most likely use the latest stable release. If you can't because you are using a new Moose functionality, then it is your responsibility as a mission designer to generate the static Moose.lua to distribute with your mission (or to wait for the next release).

I think I understand that you would want the dynamic Moose.lua to be timestamped. This is not usefull as the best way to tell what version of MOOSE you are using is Git ! This would even be negating one of the huge advantages of the new release cycle, which is that contributors don't have to generate a new Moose.lua eveytime they pull request or commit.

 Git will tell you the last commit of the branch you are currently working on with the command `git log -1`. There, you can find the hash of the latest local commit on the branch you are working on ; this is your Moose version.

I'm open to other suggestions if the Git method to get the version of Moose in dynamic is too complicated for the average contributor/beta tester.

**Comment by Delta-99** [comment]
No, I am saying that the Moose dynamic timestamp is somewhat useless - 'Moose Generation Timestamp: 20170424_1257' 

Not easy from that for me to find the GIT version or branch that I'm working on. I constantly change branches whether it is for testing functionality or what have you. Yes, you can probably find it by searching through history or something but also I may have generated the moose dynamic myself cause I typically create a static version from time to time so my timetamp will be different and not align with ANYTHING.

So, it would be much better to timestamp with the GIT version hash if this is possible. In the SVN world this would be dead simple but I understand in the GIT world they have some reason to not use keyword expansion in source files. I never bought that and issues like this definitely show me that is a big mistake.

In any event, this came about because @thebgpikester either didn't know exactly what branch he was using or we didn't communicate clearly how to determine. I LIKELY did but couldn't remember if I created my mission with the latest dev version or what dev version or what branch. It was done by mistake cause I would normally send someone a version with a static moose.

So we had no way of knowing if we were comparing apples to apples. Other factors like my computer getting messed up didn't help.

Now, if we want to help anyone out there who is a tester or working with a particular branch then it would be extremely helpful to know based on the "stamp" that is in the moose.lua file in the mission.

**Comment by Grey-Echo** [comment]
This is interesting. Here is my idea.
We could use a Git hook (https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks) after each commit to update the last commit hash on Moose.lua.
Now, the problem is that there will be a merge confilct everytime we try to merge request, which is kinda annoying. An idea, anyone ?

**Comment by FlightControl-Master** [comment]
let us try to keep things simple.

**Comment by FlightControl-Master** [comment]
Theft first question is... What are we solving. Can we generate a hash key from the sources that we embed into a file before a commit?

**Comment by Grey-Echo** [comment]
**Everything I'm going to write below only applies to dynamic Moose loading.**

We can simply use the hash of the latest commit, no need to generate our own hash from source files.

The problem is that to solve the issue in the OP, we would need to embed this hash into a file that is distributed within the .miz file, the idea being that if someone finds a random .miz file on his computer, he can simply look at the hash, and then git reset to this specific hash and run the mission. 

The only file we currently distribute within all .miz files is Moose.lua. So the hash would need to be added to Moose.lua in on way or another. This is where git hooks come into play: simply put, everytime we commit anything, git can call a script. Our script would copy the hash of the latest commit in Moose.lua. The drawback is having merge conflicts in every pull request.

Looking into it, there may be a workaround using .gitattribute : https://gist.github.com/tmaybe/4c9d94712711229cd506

**Comment by Delta-99** [comment]
@Grey-Echo, yes I guess this only would apply to dynamic since static is really only built for releases is it not? For static we might want to embed a Moose Release version manually perhaps.

So, back to dynamic, using a hash is the right way to go. Using a hash generated by source probably won't work because when you think about it Moose Dynamic doesn't change that often really. But the idea is to know what version from GIT it was generated from.

I wonder if you want to go so far as ignoring merge conflicts. What happens in a case where the conflict is actually legit? Or will this happen. I'm trying to think of cases where that might happen. I suppose the only time that would happen is if the creation of dynamic failed in a significant way!

**Comment by FlightControl-Master** [comment]
Although all this is interesting, i personally prefer at this moment to focus my available time on functionality. Investing hours to efficiently create a time stamp is a bit too much time spent from my side.
Also, a commit should be efficient, smooth, and without workarounds if possible.
We came from a commit process where every time we had to regenerate a complete file before every commit and it was too much overhead, and on top, it was creating unwanted conflicts when dealing with merges.
I will look into the idea above but want to question the urgency of this requirement.

**Comment by Grey-Echo** [comment]
> I guess this only would apply to dynamic since static is really only built for releases is it not? For static we might want to embed a Moose Release version manually perhaps.

Exactly

> The idea is to know what version from GIT it was generated from.

That's why we would need the hash of the latest commit

> I wonder if you want to go so far as ignoring merge conflicts. What happens in a case where the conflict is actually legit? Or will this happen ?

Exactly. This should never happen, as Moose.lua is automatically generated. If we ever have a problem, we can simply regenerate it. I don't think it ever happened till now. To be clear, I'm talking of ignoring merge conflicts ONLY on the `Moose Mission Setup\Moose.lua` file. Note that we can still spot any stange problem with this file BEFORE the pull request is accepted, and ask the contributor to regenrate it correctly. It is just not blocking the merge anymore.

> We came from a commit process where every time we had to regenerate a complete file before every commit and it was too much overhead, and on top, it was creating unwanted conflicts when dealing with merges.

As we discussed on Slack, either I find a way to make it transparent for the contributors, or it is not going to be implemented at all.

**Comment by Delta-99** [comment]
I don't consider this urgent but I do consider it important because it is a helpful way to tell that you are comparing apples to apples.

If this is done with a git hook then it should be relatively simple to implement. Leave it to @Grey-Echo FC so that you are not distracted by this. As @Grey-Echo has said, if it is not transparent to contributors it won't be implemented.

BTW, perhaps keep the timestamp and this thing. Doesn't hurt to have both.

**Comment by Grey-Echo** [comment]
I've been looking deeper into this one. This is doable the way I described, but there is a catch: Everyone would need to add a few lines in their .git/config file. There is no way to update this file automatically with Git, it would need to be done once manually by everyone. 
There is also no way to enforce this. 

Given the fact that any step added to the setup process (which is already pretty long) is a potential problem for the new user, and given the small added improvement, I'm wondering if it is worth it. 

For those interested the hook "pre-commit" looks like this : 
``` bash
hash=$(git rev-parse --verify HEAD)

sed -i "/Moose Previous Commit/c \env.info( 'Moose Previous Commit : \\$hash' )" "./Moose Mission Setup/Moose.lua"
echo hash = $hash
echo hash updated in MOOSE\\Moose Mission Setup\\Moose.lua
```

**Comment by baluballa** [comment]
This is old.
