### ISSUE TITLE
Respawnable wingman

### ISSUE THREAD

**Issue by FubarBundy** [FlightControl-Master/MOOSE#488]
I would like to be able to make a respawnable unit behave like a wingman. It would need follow the usual wingman commands etc... (plus any others that could be added), and would stay alive even if the client / player left the slot / role.

**Comment by FlightControl-Master** [comment]
heum ... this one is interesting. I think i could pull this one off. But just a question, this is for training or for a mission design?

**Comment by FubarBundy** [comment]
Hi sven. It's for both. Really though  it is so that a client has the opportunity to take an Ai wingman in multiplayer. Presently the wingman will despawn if the client leaves the slot or will respawn with the client and this is no good for multiplayer.  I was hoping for a wingman that stays persistent until it is actually killed or Rtb

On 2 May 2017 04:45, Sven Van de Velde <notifications@github.com> wrote:

heum ... this one is interesting. I think i could pull this one off. But just a question, this is for training or for a mission design?

**Comment by FubarBundy** [comment]
Oh and also the present wingman  system can't re-arm or refuel. The moose wingman could simulate this by simply respawning as required

On 2 May 2017 04:45, Sven Van de Velde <notifications@github.com> wrote:

heum ... this one is interesting. I think i could pull this one off. But just a question, this is for training or for a mission design?

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In 14 Nov 2018 the last commit to Moose 2.4 stable was made on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
