### ISSUE TITLE
POINT - No matter how I attempt to call GetRandomVec3InRadius it generates an error

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#546]
I've tried about 20 different ways of calling GetRandomVec3InRadius including 2 from users that apparently have had it working in the past and it still generates an error in point.lua. Same error for all the 20 different ways I have tried.

I'm using the current dev version of Moose as of May 23 2017. To be exact, this version: fb1e9972a55adfabfa9f2de11005b1c9de85d9e2

Sample code:

>   local playerUnit = CLIENT:FindByName("BLUE F15C 1-1")
  local playerPos = POINT_VEC3:NewFromVec3(playerUnit:GetVec3())
  local randPos = POINT_VEC3:NewFromVec3(playerPos:GetRandomVec3InRadius(10000, 5000))

generates the following error in Moose. Again, this error is consistent no matter how I use this method.

> 00833.014 ERROR   SCRIPTING: [string "Scripts/Moose/Core/Point.lua"]:1033: attempt to call method 'GetRandomVec2InRadius' (a nil value)
stack traceback:
	[C]: in function 'GetRandomVec2InRadius'
	[string "Scripts/Moose/Core/Point.lua"]:1033: in function 'GetRandomVec3InRadius'

Also note, I've debugged and checked the values of playerUnit and playerPos and they look fine or are at least in 20 different tests give me what I expect.

**Comment by Delta-99** [comment]
Tested with master-release version as this seemed like an old enough version and an easy version to switch to in GitHub desktop. Unfortunately I don't see an easy way to switch to any of the released version unless FC makes an actual branch for them as well. Tags are not picked up by the desktop version that I can see (major flaw in it if you ask me).

BUT, the good news (in some ways) is that things work perfectly fine there. SO somewhere between this master-release version and anything lately broke this function.

**Comment by FlightControl-Master** [comment]
@Delta-99 because of the developments to implement the settings and to be able to show on the fly coordinates in different strings from different coordinate types, I had to rework internally the POINT_VEC2 and POINT_VEC3 classes. I refactored it a bit, and I think the result is now even better structured.
I introduced a new class COORDINATE, which is the base class for all coordinate calculations. POINT_VEC3 and POINT_VEC2 derive now from COORDINATE.
But what I've also done is, in the old version, POINT_VEC2 derived from POINT_VEC3, and I've deleted this inheritance, because it is ambiguous and error prone.
Now POINT_VEC3 and POINT_VEC2 are unrelated to each other, which is much better.
As a result of this change, some methods which previously worked, now appear with an error, like this one. I've done my best to test as much as possible this core change. This is a case that I've overseen. Sorry for that.

Fixing it at this moment.

**Comment by FlightControl-Master** [comment]
A fix has been pushed with pull request #547

**Comment by Delta-99** [comment]
@FlightControl-Master great stuff. At least we know for sure what the cause was. I was actually thinking it was something like that and I was looking back through the POINT changes but didn't notice this decoupling of the inheritance. I do know what I need to do though. LEARN basic LUA classes!!! I have just been ignoring that so far but should get to know it better!!!

**Comment by FlightControl-Master** [comment]
Let me know if it worked.

**Comment by Delta-99** [comment]
Just tested in the branch for the fix and working. Found another bug and will post.
