### ISSUE TITLE
Generic randomize function with probabilities

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#564]
I think @FlightControl-Master built something for Zones specifically that allowed to pick a random zone with probabilities defined. I can see this being useful as a generic function for any sort of random choice where one wants to set probabilities.

So I guess this is an enhancement request to have such a utility function in Moose:

An example call might look something like this or whatever FC comes up with or whatever it is like for Zones. I forget how it is defined and no time to look it up right now:

`randomChoice = UTILS:randomWithProbability({"something", 0.5, "something else", 0.5})`

**Comment by FlightControl-Master** [comment]
Ha! you wanna return an item value or string, based on a randomization between a distribution in %-tages, correct?

**Comment by Delta-99** [comment]
Correct. You are doing this in one of the Randomize Zone methods I believe. I suspect would be the exact same logic just for a generic situation.

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In 14 Nov 2018 the last commit to Moose 2.4 stable was made on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
