### ISSUE TITLE
DESIGNATE: Cause little lags on AI planes

### ISSUE THREAD

**Issue by PorcoRosso86** [FlightControl-Master/MOOSE#630]
We have noticed that designate did some lags on AI (airplanes) when start to lasing a ground unit. When lasing stopped, the lag finished.

**Comment by FlightControl-Master** [comment]
I think I know what is the issue here... @EasyEB had the requirement to make the lase "jitter", so when targets are lased, I am actually on a continuous basis changing the location of the lase point (multiple times a second). This may have a performance impact.

- [ ] I think I can solve this by making the lase by default permanent to a point, unless the target unit has changed location (then move).

- [ ] And make the jittering an option. That means that lase by default will be stable, but if the MD wants, he can jitter. A method will be added to configure the jittering.

- [ ] Will also need to check for unnecessary loops if any (code check).

**Comment by FlightControl-Master** [comment]
I did a fix and lowered the refresh requency of the lasers. Now they are re-positioning the lase every second, instead of every 0.2 seconds. Can you check please?

**Comment by FlightControl-Master** [comment]
@PorcoRosso86 have you tested this and is it okay?
