### ISSUE TITLE
AI A2A dispatcher - AI utilize Tankers when available

### ISSUE THREAD

**Issue by Beamrider14** [FlightControl-Master/MOOSE#631]
Is it possible to have AI CAP utilize tankers when available verses returning to base?

**Comment by FlightControl-Master** [comment]
For that a new functionality needs to be added, that will redirect the AI to refuel instead of RTB.
I guess something in the lines of:

- [ ] adding a new method to the AI_A2A_DISPATCHER:SetSquadronTanker( GroupTanker ).

- [ ] make the AI fly to the Tanker before a certain fuel treshold is reached (default = 20%) and refuel.

- [ ] after the refuelling, the AI should continue the patrol.

- [ ] this to be defined per squadron.

**Comment by FlightControl-Master** [comment]
@Beamrider14 This is going to be my next project, add a state "Refuelling", and make the AI fly to the nearest tanker, instead of RTB...

**Comment by FlightControl-Master** [comment]
@Beamrider14 Hope you like the new development for the refuelling :-)

**Comment by FlightControl-Master** [comment]
Implemented, closing
