### ISSUE TITLE
Tracking Bullets Fired

### ISSUE THREAD

**Issue by Zook3r** [FlightControl-Master/MOOSE#649]
Create the ability to keep track of client accuracy, calculated as hits/shots fired. Currently the functionality is limited to detecting and counting the bullet for each shooting event that is more than a certain time after the previous event. This could be used to give points based on accuracy percentage or used to track for an external stats page.

**Comment by FlightControl-Master** [comment]
@Zook3r Thanks for this write-up. Going to check the design and embed this into SCORING (class).

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In 14 Nov 2018 the last commit to Moose 2.4 stable was made on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
