### ISSUE TITLE
CAPs Still Not Engaging Appropriately In Latest Release - 20170902_1027

### ISSUE THREAD

**Issue by Invisibull** [FlightControl-Master/MOOSE#677]
In test I had two CAP flights originating from Groom Lake and two from Tonopah.  I flew over Groom Lake roughly 10 nm away from both CAPs and neither paid any attention to me.  However, one of the flights from Tonopah, 50 miles away, did begin engaging.  

[dcs.txt](https://github.com/FlightControl-Master/MOOSE/files/1277648/dcs.txt)

**Comment by FlightControl-Master** [comment]
Aha! And it the area covered by ewr?

**Comment by thebgpikester** [comment]
Only thing I can add is that can you verify that the CAP nearest wasn't either engaged, or RTB soon, ie were you the only person there and can verify they were available, since Dispatcher does do some heavy thinking when he dispatches.

**Comment by shadowze** [comment]
Would it be possible for the next version of MOOSE
When using AI_A2A_GCICAP
Could the spawned planes have their names changed to have either CAP or CGI in it
that way I could report when observing live MP missions who is attacking what

**Comment by Invisibull** [comment]
FC - yes.  there was plenty of AWACs and radar coverage in the area.  I'd assume that's how the Tonopah group got assigned.  

Pike - I was the only blue flight in the air.  This is from the dcs.log:

Tactical Overview

 - Target AREA.1 ( 1 ): ( #1 ) Pilot #062, 
   - tonopah_23#002 ( CAP - Engaging ): ( #2 ) F: 108, D:100 - Executing

 - No Targets:
   - groom_23#001 ( CAP - Patrolling ): ( #2 ) F: 100, D:100 - Executing
   - groom_15#001 ( CAP - Patrolling ): ( #2 ) F: 135, D:100 - Executing
   - tonopah_23#001 ( CAP - Patrolling ): ( #2 ) F: 104, D:100 - Executing

So, i was alone in the air and the tonopah_23#002 group was tasked to engage me even though I was far closer to the groom groups.

I ran this scenario numerous times and not once did the closest group engage me.  At times i was only 5nm away and that didn't seem to make a difference.

**Comment by FlightControl-Master** [comment]
Bug confirmed and fixed and tested as we speak. @Invisibull is testing now the fix.

**Comment by FlightControl-Master** [comment]
@Invisibull thanks for testing, can you confirm this is fixed?

**Comment by Invisibull** [comment]
Unfortunately, it seemed to be working fine at the beginning of a 6 hr long MP mission.  I left mission after about an hour, and when i returned at about hour 4, someone on the server reported that none of the ai were engaging or maneuvering before he shot them down.   I then observed the same effect myself.  I will continue testing, but this seems like the same bug, just delayed as things worked fine during first hour.  I would add that I'm trying to integrate the warehouse system into my mission so perhaps that has some effect as well.  I'll remove that from the equation and see if ai begins to consistently engage again.

**Comment by FlightControl-Master** [comment]
It won't be the same bug. It will be a different cause. Please drop your dcs.log.

**Comment by FlightControl-Master** [comment]
@Invisibull For your information, @shadowze is running the A2A dispatcher on a 24/7 basis and has an average of 10 to 20 players on the server at the same time ...
He is automatically forwarding the dcs.log files to a cloud server. And I am checking upon those for any crashes that occur.
Checking the last run of 8 Sep 2017 on his server, I found a few crashes:

![afbeelding](https://user-images.githubusercontent.com/13690775/30201672-eae87068-947b-11e7-80e1-6c5049dec2fb.png)

So I will investigate those and see if these can be resolved.
The crashes are most likely because of players exiting their plane or disconnects and resulting in script errors. I need to ensure that all these weak spots have proper handling of these kind of events.

This is a tedious task and will take a bit of time to stabilize. Just know we are working on that.

FC

**Comment by Invisibull** [comment]
Thx FC, here's the log - 

[dcs.txt](https://github.com/FlightControl-Master/MOOSE/files/1287670/dcs.txt)

To reiterate, in the first hour or two the AI was fierce.  Very aggressive.  Upon re-joining the server in the 4th hour, the ai refused to engage.  I should note that there was plenty of EWR coverage and the ai were within their own border area, and designated CAP areas when this happened.

**Comment by FlightControl-Master** [comment]
thanks!

So the CAP engagement logic is implemented and works. That is proven.
What we have now probably are "leaks" or "unhandled exceptions" in the logic, especially in the multi player environment. It can be that an exception occurs and the logic "stops". And then of course planes might stop engaging because the dispatcher may have stopped or because one of the plane AI governors may have halted.

I'll provide feedback.

**Comment by FlightControl-Master** [comment]
by they way @Invisibull this morning I checked the log of @shadowze server and identified 3 problems that i fixed. Don't know if you wanna do a server run again, but if you do, please ensure you incorporate these fixes too by loading the latest version of moose.lua from the release page.

**Comment by FlightControl-Master** [comment]
@Invisibull what is this error?

`DCS: Mission script error: : [string "C:\Users\WoP\AppData\Local\Temp\DCS.openalpha\/~mis000076A2"]:27010: SPAWN:New: There is no group declared in the mission editor with SpawnTemplatePrefix = 'lincoln_15'`

Seems like you added a new group in your script, which is not known in the editor.

**Comment by Invisibull** [comment]
yeah, that's interesting, FC.  I removed any mention of lincoln_15 from the mission lua but it still looks for it.  
It's like it's become embedded in the .miz and can't be changed.

**Comment by Delta-99** [comment]
Hey this is great that @shadowze is doing this. Is this server open to the public or is it private to his group?

**Comment by FlightControl-Master** [comment]
Solved.
