### ISSUE TITLE
DCS-BUG-5 - S_EVENT_PLAYER_ENTER_UNIT not fired in MP when entering CA unit.

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#692]
https://forums.eagle.ru/showthread.php?t=206069

https://forums.eagle.ru/showthread.php?t=186666

**Comment by FlightControl-Master** [comment]
A scripting engine issue...

In a multi player setup (MPS), when a player enters any unit from a client connected PC, the event S_EVENT_PLAYER_ENTER_UNIT is not fired on the server!

When a player enters a slot (a plane) from a client connected PC, the S_EVENT_BIRTH is fired on the server, which is okay. But again, no S_EVENT_PLAYER_ENTER_UNIT is fired on the server.

When a player enters an already alive unit using the CA module (so on the map, select a unit and press ALT-J) on a client connected PC, the S_EVENT_PLAYER_ENTER_UNIT is not fired on the server.

This is a problem, because there is no CPU efficient way to know when a player enters a unit in a MPS.

The event S_EVENT_PLAYER_ENTER_UNIT is correctly working in a SP setup though. As a workaround, the only way now for me to know if a player is in a unit or not, is to iterate through the set of units and check the player name, and do this continuously. This is not ideal ...

I will leave it up to DCS developer team to evaluate the urgency of this issue. I can imagine that testing and fixing this may require some effort.

FC

**Comment by FlightControl-Master** [comment]
Guys, I am in contact with ED regarding this issue ... Just wanna let you know ...

> Hello sir(s),
> 
> Since quite a long time there is an existing problem with the CA module of DCS world.
> 
> The event S_EVENT_PLAYER_ENTER_UNIT does not get triggered in the DCS simulator in a multi player environment *on the server*, when a player enters an existing, alive CA unit using ALT-J (from the client).
> 
> Although this problem may not seem like a showstopper or a huge issue at first sight, it does bring issues for a growing MOOSE framework user community.
> 
> The framework has a tasking system, which is currently working for A2A and A2G tasking, and further tasking categories are under development.
> 
> The tasking system allows players to join a task, and while seated in a unit, he will execute the task goals. Essential is:
> - that the Unit in which he is seated and the player name need to be able to be queried with Unit:getPlayerName()
> - the moment when the player joins a unit, that this is detectable (S_EVENT_PLAYER_ENTER_UNIT)
> 
> The MOOSE system is designed as follows:
> 
> Upon the moment a player joins a unit, a menu configuration system is fired off, that sets per group that is assigned to the task a series of menu items for the group. The player can use these menu items to command or require status of the task for the group he is seated in. Messages are sent to the group showing status information or set markers on the map and so on.
> 
> On a multi player environment, this is working perfectly for air units (planes and helicopters) but not for CA units.
> 
> When a player joins a CA unit (tank, sam) from the map (ALT-J) the event S_EVENT_PLAYER_ENTER_UNIT is not triggered, and neither is it possible to enquire the player name that is seated in the CA unit.
> 
> So there are actually two problems that are already reported (a long time ago):
> - issue 0026597 in your DB, which is related to the S_EVENT_PLAYER_ENTER_UNIT.
> - an unknown issue, which is related to Unit:getPlayerName() returning a blank string in multi player on the server.
> 
> *In the name of the users of MOOSe, we have the following request:
> 
> *- Would it be possible to consider if these issues could be fixed? 
> - What is the issue exactly that plays? Is this is a huge implementation that needs to be done, or is it about looking into it and checking an error in the logic that may exist? 
> - Has a bug complexity assessment already been done on this item? 
> - Is there a planned fix for this issue?
> - Are there dependencies that prevent this issue to be fixed?
> 
> 
> *The value add for ED if this gets fixed:
> *
> If these issues would get fixed, a whole new era of CA players can enjoy the game using the MOOSE framework, by executing ground task objectives, like capture zones, advanced tasking of ground targets, scorings generated, messages generated to CA units etc.
> 
> In other words, this will allow the CA module to grow in utilization excitement for players.
> 
> MOOSE is a growing community and people have been reporting me these issues if these could be fixed.
> 
> Ground operations for players are not functional using the MOOSE tasking system until these issues get fixed. For the MOOSE framework, this is a show stopper.
> 
> http://flightcontrol-master.github.io/MOOSE/
> 
> 
> Please consider this request and if any further information can be shared, please do.
> 
> Thank you and kind regards,
> Sven
> ---End Quote---
> Hello Sven,
> 
> I'll ask programmers on Monday about current progress of this issue and give you answer then.
>
