### ISSUE TITLE
DESIGNATE: Be able to smoke targets while lasing ...

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#700]

**Comment by FlightControl-Master** [comment]
@ramsay This was your requirement:

> I'm not sure if it's possible to smoke and simultaneously lase a target using DESIGNATE (smoke followed by lase perhaps?), I'll need to test some more before giving further feedback.

**Comment by Ramsay58** [comment]
@FlightControl-Master 
>I've moved this for an enhancement in release 2.3.

Thanks, most of it is already possible in 2.2.0 pre.

- Call for a smoke mark first - the smoke persists for 5 minutes
![area_1_smoke_screen_170921_014246](https://user-images.githubusercontent.com/31033413/30675632-8059b682-9e79-11e7-8d9a-5b9604e5f2ae.jpg)

- then call for a laser 
![area_1_lase_screen_170921_014342](https://user-images.githubusercontent.com/31033413/30675663-a7ad1fc6-9e79-11e7-88f8-1fcb7f1e22f0.jpg)

it timesout after 60 seconds in build 20170918_1451
![area_1_lase_timeout_screen_170921_014413](https://user-images.githubusercontent.com/31033413/30675699-db0b212e-9e79-11e7-93f9-5c63f3669cff.jpg)

but there's a WIP bug in build 20170918_1451 as the designate laser menu/status doesn't update when lasing times out.
![area_1_laser_timeout_menu_bug_screen_170921_014442](https://user-images.githubusercontent.com/31033413/30675804-815f46d6-9e7a-11e7-9d41-18a0d714b594.jpg)

There probably should be a status message if the JTAC (Predator) loses line of sight and **stops lasing** as the player should be given the chance to abort the bombing run or informed why the bomb didn't guide. It takes quite a while for the lost Detection LoS message to appear.

While not important for a 60 second timeout, it'd be nice if we could call for a smoke mark during lasing as well as before.

Build 20170918_1451 seems to have lost the (S) Area prefix for smoked targets, but being able to lase is far more useful

Note: To get the A2G Tasks to populate, I spawned in a M-2000C first before switching to a Game Master slot. The Designate behaviour appears the same I found flying afternoon air missions but it's easier to confirm the laser behaviour at night.

I used the M2A2 Bradley as I had trouble get detection, laser and smoke markers working using the A-10C/SA-342M however the mission was designed/tested for daylight operations, so my initial problems may be due to recon.

**Comment by Ramsay58** [comment]
I'll include DCS log from this morning. Attack A-10C, Attack SA-342M and Attack M2KC are player slots for testing MOOSE. Attack Maykop 1, 2, and 3 are AI M2A2 Bradleys that I take control of when taking the GAME MASTER slot.
[dcs_log_20170921_designate_laser_menu.zip](https://github.com/FlightControl-Master/MOOSE/files/1321354/dcs_log_20170921_designate_laser_menu.zip)

**Comment by FlightControl-Master** [comment]
Excellent. I will consider all this.

**Comment by FlightControl-User** [comment]
Fixed... in latest MOOSE_INCLUDE repository. Please clone this repo.

**Comment by Delta-99** [comment]
@Ramsay58 is this fixed for you now? Can you test and confirm?

**Comment by FlightControl-User** [comment]
@Ramsay58 this is implemented and fixed. designate is perfectly working now! have fun!
