### ISSUE TITLE
MENU: MOOSE seems to delete menus in the root! This should not happen!

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#731]

**Comment by FlightControl-Master** [comment]
Re-Created the complete menu handling system.
I've removed the possibility to remove the "parent" menus when a child menu would be removed.
That however will require to update the complete menu structure by the mission designer when one menu item in a hierarchy needs to be removed, but considering the "danger" of parent menu implementations, it is the recommended approach because otherwise we risk that parent menus are accidentally deleted that shouldn't have been deleted at all!

**Comment by FlightControl-User** [comment]
Fixed
