### ISSUE TITLE
Missile Trainer not working

### ISSUE THREAD

**Issue by 132nd-Entropy** [FlightControl-Master/MOOSE#761]
Hello, the missile trainer stopped working for us, however I never got an error in the log. After systematically disabling all our other scripts and functions, I came to the conclusion that it is the mooose.lua version that must cause the problem. 
By systematically rolling back to all versions of moose, I found the latest mooose.lua release where the trainer is working. 
I pushed 2 branches, one where its working, one where its not working to origin. Maybe this way the problem can be identified (not sure how this would be handled better)
thanks for the help!

**Comment by 132nd-Entropy** [comment]
the latest branch where the trainer is working is called 'Entropy_Trainer_Working'

**Comment by FlightControl-Master** [comment]
OK. I will check today.

**Comment by FlightControl-Master** [comment]
I think it was due to a temporary error in SCHEDULER. I fixed a core bug in SCHEDULER and possibly this causes problems in other modules too. Actually, I need to retest all. Sorry for the inconvenience, but the error was a severe problem in SCHEDULER I had to correct to avoid further design issues in the future.

Testing at the moment.

**Comment by FlightControl-Master** [comment]
The latest master branch version should have fixed this issue. 
I have retested the MISSILETRAINER with the latest master branch version, and it works.
I have published yesterday afternoon a new **release** 2.3-alpha version with the working MISSILETRAINER.

Can you reload the latest moose.lua from the release 2.3-alpha version here, and retry. Please confirm if your issue is fixed or not:
https://github.com/FlightControl-Master/MOOSE/releases/tag/2.3-alpha

Thanks

**Comment by 132nd-Entropy** [comment]
I tested this with yesterdays release 2.3 alpha and while I dont get any errors, it doesnt work. Im getting the initial messages (tracking on, etc etc), and I also get a launch warning, so the trainer is doing its job, but its not destroying the missile. Im also not getting the briefing message at the beginning.

**Comment by 132nd-Entropy** [comment]
Timestamp: 20171209_1329 

is the moose.lua Im using. Easy way to test is when you join an aircraft, I dont get the inital briefing message

**Comment by FlightControl-Master** [comment]
Is this one dcs 1.5.7???

**Comment by FlightControl-Master** [comment]
Issue fixed in release 2.3-alpha.
