### ISSUE TITLE
Feature Request - CSAR Module for MOOSE to enable easy config of helicopter rescue of downed pilots

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#764]
Hi Sven
 I would like to have an easy to use module to enable CSAR in MP missions for heli pilots to select a rescue
mission and then go and retrieve a pilot in the field,
Pilots would transmit a homing beacon to enable location (could also use smoke or flare if vis low)

Ciribob CSAR script seems to rely upon real human pilots getting shot down, I just want to be able to use AI pilots not real human ones

**Comment by FlightControl-Master** [comment]
@132nd-Entropy has made something. Yes, this would be a great addition in MOOSE.

**Comment by Delta-99** [comment]
Actually CIRIBobs CSAR script works really well with AI pilots being shot down. I use it all the time. It might be default to NOT be setup that way but it’s certainly possible.

**Comment by FlightControl-Master** [comment]
Yes @Delta-99 but I know where the request from @shadowze is coming from :-)

**Comment by Delta-99** [comment]
No worries. Just wanted to point that out as Shadow said it wasn’t supported in that script.

**Comment by FlightControl-Master** [comment]
ha!

**Comment by shadowze** [comment]
How would I spawn a AI blue plane for a second then destroy it so I would have a pilot to rescue ?

**Comment by Delta-99** [comment]
I believe there is an example mission as part of Ciribobs script (or I snagged it from somewhere else). But basically what it did as far as I could tell was have BLUE AI planes fly over overwhelming ground forces that would shoot them all down pretty easily. Then I think the ground forces were de-spawned once they were done their job. At least for Ciribobs script, it hinges on pilot ejection so unless you can trigger that somehow via script (which I highly doubt) then you are out of luck. I believe if the plane gets destroyed and pilot killed before they get to eject then there is no pilot to rescue.

OR if you are simply just attempting to simulate picking up a downed pilot then you can figure out what the script does AFTER ejection and do the same thing. It basically spawns an infantry unit on the ground as far as I know after ejection.

**Comment by thebgpikester** [comment]
I tried this once, I found it unreliable. if you spawn a plane without fuel the pilot doesn't always eject and there is also a small delay. Then I suppose you could delete the spawn to clean up. Not sure if it's easy enough to catch the eject or you have to guess.

**Comment by Delta-99** [comment]
I guess it depends on what you are trying to do. It sounds like you guys are attempting to simulate an ejection rather than having it happen for real. If that is the case it doesn't really help you any because an ejected pilot is not available as far as I know by anything in the scripting world or even in the mission really I don't think. So its not like you can actually pickup that pilot. These scripts spawn a "new" unit simulating where the pilot dropped to the ground. This is why you'll sometimes see the real ejected pilot and the simulated one.

**Comment by dwpenney** [comment]
I was planning on doing something like this in the new year. I had worked on a project to implement during the early phases of the CSAR work being done my the community (3 or more years ago). I had a framework all figured out and during the preparation for the latest Mudspike fly-in, thought that it would make a grand addition to the sand-box missions that we have.

The way I handled the ejections (and I think that this was the general way to do it a few years ago) was to spawn a representative infantry unit under where the ejection event occurred. I then attached a radio transponder beacon to the unit so that the UH-1H could track towards it. When the rescue unit entered a hover a few meters off the ground (or landed) the rescue unit would spawn a CSAR team to go to the 'downed pilot' and escort them to the rescue chopper. When the rescue unit returned to the FARP, they could disembark the CSAR units.

As I said, I plan on revisiting this idea in January and merge it into the MOOSE framework as best I can. If someone else wants to run with the idea, feel free :-)

**Comment by Delta-99** [comment]
There may have been a discussion with Ciribob on this as well a while back. FC might have info on that.

**Comment by FlightControl-Master** [comment]
Explode a plane with small explosions until the pilot ejects

**Comment by TracerFacer** [comment]
I took the CSAR script, turned off all the dynamic spawns from clients and destroyed ground targets,  and instead spawn a bunch of manual ones randomly throughout the mission area. I then add 1 to a flag every time a rescue occurred, and when that flag got to 30, mission complete. 

Great script! 

Plays along side ctld and moose nicely. 

I'd like to tie that into moose scores somehow.
