### ISSUE TITLE
SPAWN: Feature Request/Semi Bug Randomized Ground Spawns need to check for valid terrain types.

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#792]
At the moment any form of randomized ground spawning does not appear to check for a valid spawn ground type.

This leads to issues where you can have various units spawn in the water etc. 

It would be nice to have MOOSE do a check when it does a randomization of the spawn locations be it by Zone or even just InitRandomize for surface types. 

land.getSurfaceType(vec2) returns the surface type so if ground spawns could check for a return of 3 (WATER) it would prevent them spawning in the water

It would also be nice if we could have 2 extra boolean flags in the randomizations for Shallow_water (2) and RUNWAY (5) that would give far more control over both Zone and Randomize spawns as you could at least prevent a unit from spawning where it would immediately cause an issue (like on the end of a runway)

It's just at the moment we are seeing things like the attached image happen with randomised position spawning which can be a nightmare to deal with 
![unknown](https://user-images.githubusercontent.com/28775608/34650797-c6d99036-f41a-11e7-97a9-65f0dee4d92e.png)

**Comment by Delta-99** [comment]
I would take this a step further and rather than checking for NOT water should check for a valid area. Or, maybe want to specify what to spawn on so that you can have units spawn on a road only if you gave it that option. Also, I believe units will spawn on top of buildings so maybe a check for that too if possible!!! However, I have seen folks wanting to spawn units on top of buildings at times so once again something optional that covers all potential desired outcomes.

**Comment by thebgpikester** [comment]
yes terrain validity entirely, slope of hill can be an issue (hopefully not so much with 2.5. Rivers in 2.2 are currently something you can spawn a tank 10ft under water with.
For spawning on a building I think there is a check for altude under a coordinate, but it seems that a range of options have to be looked at, with some customisation as there's always someone (usually me) that wants a non standard approach.

**Comment by Delta-99** [comment]
With 2.5 and tree's I was hoping there was a land type that designated "forest" or something along those lines but doesn't look like it. Unfortunate because spawning stuff in a forest MIGHT be desired OR NOT.

I was using this reference: http://wiki.hoggit.us/view/DCS_func_getSurfaceType

Note, there is other good stuff too if you wanted to add spawning on closest road segment or something by using this: http://wiki.hoggit.us/view/DCS_func_getClosestPointOnRoads

**Comment by FlightControl-Master** [comment]
hmm... I agree about the issues. The question is, how to fix it ... I know about the getSurfaceType. But not sure that covers everything.

**Comment by Delta-99** [comment]
There is no way to find trees and I've put in an enhancement request for that or asked Grimes where is the best place to do that. BUT, I wouldn't hold my breath on it ever being implemented.

However, I think we can easily handle some of the other like making sure not spawned in water etc. Yes, need to think what happens if a suitable spawn location is NOT found at all and things like that.

Just forget the things that are too hard or possibly impossible. So, implementing just the first request of NOT spawning in water or spawning on land would be a MASSIVE help right now.

**Comment by thebgpikester** [comment]
BTW, no need to avoid trees. They avoid _you_ in 2.5

Yes, place an object, they disappear. You also have the ability to delete them in a zone.

**Comment by Delta-99** [comment]
@thebgpikester what do you mean by both statements?

I have heard about this disappearing object thing but have not witnessed it yet. I place lots of ground units randomly in my missions and nothing has disappeared yet. They spawn perfectly fine like they always do. The only difference is now if they spawn in a forest (and do not move) I'm not entirely sure they can fire out of it or be seen from aircraft. More testing is required. I think I have found aircraft take just a lot longer to find those targets which is perfectly fine to me.

However the point of the request makes a lot of sense given you might want stuff spawned out in the open (or in a forest)!!!

**Comment by Delta-99** [comment]
Grimes put in a request to have mor options returned by this function. Like what I asked for and also for buildings. Maybe we will get something but still not holding my breath!!

**Comment by thebgpikester** [comment]
OK, there is a way via ME to delete a patch of forest and trees in a zone. Along with the same method you can remove ALL MAP OBJECTS! Same as in Arma, almost identical.

However if you place a farp (untested other models) and it collides with trees, the trees are removed automatically. Hope that makes sense. Will be good to expose this to the SSE but I do not see the functions in hoggit.

**Comment by FlightControl-User** [comment]
I will see if I can do something with getSurfaceType as a start. Units shouldn't be spawned above the sea.
