### ISSUE TITLE
TASK_A2G: QFE in Task Report

### ISSUE THREAD

**Issue by DanWithUsernameNotAlreadyTaken** [FlightControl-Master/MOOSE#814]
Hello,
is it possible to add the qfe for the target units in the task reports? Maybe after the Coordinates.
Or is there some way to add a line to the task reports with the mission script?
Thanks in advance!

**Comment by FlightControl-User** [comment]
@DanWithUsernameNotAlreadyTaken @funkyfranky @thebgpikester 

I suggest the following design, because there are two aspects to this:

  1. The qfe calculation of "targets".
  2. The display of the qfe.


1. The qfe calculation of "targets".

The qfe calculation should be very straightforward, and can be done any time. The question is exactly where should the qfe be calculated. There are several locations were qfe could be useful.

- DESIGNATE class
- A2G TASKING classes
- A2A TASKING classes

On top, should the qfe always be calculated, or, could it be requested to be calculated based on a menu option?

2. The display of the qfe.

Then we have the configuration of it. The qfe parameter could be displayed, but I can imagine that certain people would not like this to have displayed all the time. It takes place, it may disturb people of "too much information".

Therefore, I can imagine some kind of setting as part of the SETTINGS class, that manages this qfe calculation. When switched on, it could be displayed where appropriate, where it would not be displayed when switched off.

Is it to be displayed all the time, or just at the briefing? Is the QFE to be calculated for every target, or just for a group of targets? ...

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
I will write what would fits best for me:
The QFE should be in the tasking classes not in designate. This is because of the MOOSE functionality of CONTROLABLEs and the improvement of the DCS "vanilla" JTAC, which i use usually. Which type of FAC and designation one uses is up to his own and so i would put it in the Task reports to be not dependant of the MOOSE designation and for easy use as additional information near the coordinate line of these reports. Or maybe just put it in both DESIGNATION and A2G_TASKING. 
IMHO is QFE a part of the coordinates of the target in the TASK reports and should be displayed every time the coordinates get displayed e.g.: "Coordinates: LLDM, 42.32.123'N 41.47.122'E QFE, 29.92" or something like this.
I would think a simple switch in the SETTINGS menu should be added where the client can choose if QFE is displayed in the Task reports, just like the setting of the coordinate system.

"Is the QFE to be calculated for every target" - I think this should be handled like the coordinates as it seems to work fine.

**Comment by FlightControl-User** [comment]
@DanWithUsernameNotAlreadyTaken I hear you and working on it now ...

**Comment by FlightControl-User** [comment]
@DanWithUsernameNotAlreadyTaken I've implemented it now and followed your advice.
So, I've right now added the °C, QFE and Wind at the report of each target location.

The result in the report looks like this:

**For the task Overview Report**
![screen_180303_055453](https://user-images.githubusercontent.com/13690775/36930736-e2bdd08e-1ea7-11e8-8e73-ef43f98cfa24.png)

**For the task Detailed Report**
![screen_180303_055529](https://user-images.githubusercontent.com/13690775/36930738-e6c9af40-1ea7-11e8-8284-b3cbf5b5d965.png)

I need to look why these trailing '-' are not positioned correctly at the Detailed Report, but that is a minor issue.

You can test yourself, because I already published this change to the master branch. You can download and embed the Moose.lua containing this change from the following repository:

https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/master/Moose_Include_Static

Download the latest Moose.lua from here, and add it into your mission to test the change.
@DanWithUsernameNotAlreadyTaken Please let me know if it is correctly implemented.

Thanks @funkyfranky for the great methods you added at COORDINATE!

One small question to @funkyfranky ... In the flight world, is QFE always expressed in hecto pascal? And temperature always in degrees celcius? Because otherwise we'll also need to adapt these to the imperial and metric measurements system in SETTINGS to be consistent with the system.

**Comment by funkyfranky** [comment]
@FlightControl-User  QFE/QNH pressure units are tricky since three different are used. You have hPa (european aircraft), mmHg (russian aircraft), inHg (american aircraft). Conversion factors are
hPa2inHg=0.0295299830714
hPa2mmHg=0.7500615613030.

**Comment by FlightControl-User** [comment]
@funkyfranky So we could solve this somehow. We can always show hPA and then according the metric system selected, we can also show:

- [ ] For Russian aircraft using the metric system - mmHg
- [ ] For Americain aircraft we link to the imperial system - inHg

What figure is required for the Viggen?

And what is the difference between QFE and QNH?

**Comment by funkyfranky** [comment]
@FlightControl yes, that's probably best, always hPa and then mmHg, inHg depending on metric system.
Viggen uses hPa.
QFE is the pressure at the ground height (field elevation). That's what you need to step up you target computer in the Viggen for example. QNH is the pressure at see level. More important for navigation purposes.

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
@FlightControl-User 
Thank you for the very fast work and implementation :D
"Is it really worth to add to SETTINGS [...]" in my opinion not. I just answered on your suggestion in this topic.
I downloaded the new Moose.lua and begun testing. I wasn't able to get the qfe shown right now but i didn't figure out yet if it is dependant on my missionscript. I have some further issues in my mission and maybe my old missionscript is incompatible.

**Comment by FlightControl-User** [comment]
@DanWithUsernameNotAlreadyTaken Ensure you have the correct Moose.lua that is loaded at the beginning of your script. In the directions specified above, you need to get the latest version from the repository MOOSE_INCLUDE from the static loading directory.

Otherwise you won't see the change!

**Comment by FlightControl-User** [comment]
@funkyfranky ok. So I will implement as suggested.  Thank you for the advice.

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
@FlightControl-User the issues with the new MOOSE.lua are not dependent on my script. If i now join a mission and go to spectator, then join in a plane slot, i won't get the mission menu but i have the settings menu. If i join the mission and go directly in a plane slot i will have the mission menu (but task reports without qfe) but no settings menu. I tried this in a clean and new mission in 2.5. 
[Test.zip](https://github.com/FlightControl-Master/MOOSE/files/1777620/Test.zip)

**Comment by Delta-99** [comment]
Shouldn’t you be using the users settings on whether to show in imperial or metric?

**Comment by FlightControl-User** [comment]
@delta-99 doing exactly that.

**Comment by FlightControl-User** [comment]
Guys, I've published a reworked solution. It works now with SETTINGS.
On top, the mechanism how reports are generated are also reviewed.
Can you guys please test this and please let me know your user experience using A2G tasking (dispatcher).
In the meanwhile, I am checking the issue for Dan on the non-task A2G dispatcher.

**Comment by FlightControl-User** [comment]
So now @DanWithUsernameNotAlreadyTaken  your issue should be testable with your test mission that you posted. Find the updated mission here:

[Test.zip](https://github.com/FlightControl-Master/MOOSE/files/1780574/Test.zip)

QFE is implemented, so is wind, temperature and a complete overhaul of the report generations for tasking... I am interested in your user experiences.

The new moose.lua can be downloaded from the MOOSE_INCLUDE repository:
https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/master/Moose_Include_Static
This repo contains the generated Moose.lua and Moose_.lua to include within your missions.

All test missions have been updated with the fix. So you can retry the missions from here:
https://github.com/FlightControl-Master/MOOSE_MISSIONS
A collection of demonstration and test missions for the MOOSE Framework, packed and contains the static loader moose.lua. So these missions can be run independently.

Happy testing. Note that i've changed your A10C to a simple su-25T for me to test on vanilla installation.

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
It still doesen't wörk for me :/ As you said you tested with a fresh install, i wonder what breaks this script. At least i get the settings and the mission menu now if i go to spectators first. Maybe i should do a fresh install also :( but i won't have the time for this for at least two weaks :'(
![moosetest](https://user-images.githubusercontent.com/36799931/36995518-8b15f082-20b4-11e8-8e54-653f7f590155.png)

**Comment by FlightControl-User** [comment]
Sorry.  I had your mission  tested today

**Comment by FlightControl-User** [comment]
You're using the correct version???

**Comment by FlightControl-User** [comment]
Try overview menu

**Comment by FlightControl-User** [comment]
Planned tasks

**Comment by FlightControl-User** [comment]
Not only detailed.

**Comment by FlightControl-User** [comment]
@DanWithUsernameNotAlreadyTaken i am sorry. I have indeed another issue in the logic that you found out. I have fixed it right now and it is already updating. Give it 10 minutes! The issue here is that you aren't using any detection, just plan tasking. As such, there was a branch in the logic that did not generate the QFE etc. I should have tested this too. Anyway, an update is under way.

**Comment by FlightControl-User** [comment]
![afbeelding](https://user-images.githubusercontent.com/13690775/36997329-9d6a1e34-20b9-11e8-94a6-2fd35b63f17d.png)

**Comment by FlightControl-User** [comment]
[Test.zip](https://github.com/FlightControl-Master/MOOSE/files/1782440/Test.zip)

Can you retry?

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
OK, i'm downloading. Man you're fast oO

**Comment by FlightControl-User** [comment]
It was a silly stupid error, appologies.

**Comment by FlightControl-User** [comment]
![afbeelding](https://user-images.githubusercontent.com/13690775/36997734-e43908ec-20ba-11e8-9796-7e194bdd3302.png)

**Comment by FlightControl-User** [comment]
So... QFE, Wind, Temperature will now display BOTH for taskings that have detection and tasking without detection.
**QFE** will display on Markings, **Overview reports**, Detailed reports.
**Wind** on Markings, Detailed reports.
**Temperature** on Markings, Detailed reports.

So when you do the overview report "planned reports", you'll only see QFE, but when you do a detailed report of request a marking on the map, you'll see all details.
On the summary report of all the tasks, no QFE, Wind, or Temp is displayed.

Makes sense?

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
![mooseworks](https://user-images.githubusercontent.com/36799931/36998098-1596624e-20bc-11e8-91eb-b36dccdc2d34.png)
Yes makes sense, thank you very much for this improvement!

**Comment by FlightControl-User** [comment]
So, now you have the CC menu and the QFE. Can I close this issue?

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
Yes, i think you can close. I will do further testing with the new Moose.lua on next weekend, but it seems as it wörks as intendet. Tank you. 
.................███ ]▄▄▄▄▄▃
..▂▄▅█████▅▄▃▂
[███████████████]
◥⊙▲⊙▲⊙▲⊙▲⊙▲⊙◤

**Comment by funkyfranky** [comment]
I suggest to limit but explicitly specify the number of digits in the output. One for hPa and mmHg and two for inHg. Temperature at most on digit.
A) It enhances the readability.
B) Many people fly in VR these days. Output format is more limited.

**Comment by FlightControl-User** [comment]
@funkyfranky Can you do an example?

**Comment by FlightControl-User** [comment]
sorry, no forther it, never mind

**Comment by FlightControl-User** [comment]
I'll look into this.

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
The qfe in hPa is perfect right now. More rounding is too inacurate for the Viggen. I don't know the needed accuracy for the russian planes.

**Comment by FlightControl-User** [comment]
@funkyfranky ?

**Comment by funkyfranky** [comment]
Viggen needs one digit for accuracy e.g. 1008.4 hPa. Same accuracy for mmHg one digit, e.g. 756.4 mmHg. Imerial inHg needs two digits, e.g. 29.79 inHg.
In the picture, the conversion is wrong! inHg is displayed as mmHg.1008 hPa = 756 mmHg =29.8 inHg. 
Temperature can be 20 DegC. No one cares if it is 20.45 DegC. Meters per second also no digits since irrelevant in practice.

**Comment by DanWithUsernameNotAlreadyTaken** [comment]
A i see, i get confused with the english word "digit" every time. In german it is "Nachkommastelle", in this context i think , which is, IMHO, more accurate :D
@FlightControl-User the qfe-meter (or what ever is called) in the Viggen has only four numbers in its display (eg. 1008) but as it is analog you can fine tune it, so if you can read 1008.4 hPa as @funkyfranky suggested you can fine tune it by dialing 1008 hPa "and a lit bit more" which is indeed more accurate than only the four numbers. But this is polishing and i'm happy with the solution right now for the Viggen :-*

**Comment by FlightControl-User** [comment]
@funkyfranky. I am sure I took the conversion as you indicated:)

**Comment by funkyfranky** [comment]
@FlightControl-User No quite ;) I said
hPa2inHg=0.0295299830714
hPa2mmHg=0.7500615613030.

You have
local Pressure_mmHg = Pressure_hPa * 0.0295299830714
local Pressure_inHg = Pressure_hPa * 0.7500615613030
in the code. This should read
local Pressure_mmHg = Pressure_hPa * 0.7500615613030
local Pressure_inHg = Pressure_hPa * 0.0295299830714

**Comment by FlightControl-User** [comment]
How did this happen :) I'll fix.  Thanks for telling the mistake!

**Comment by FlightControl-User** [comment]
OK. Those last issues are fixed now.
- Accuracy of hPa to 4.1 digit, inHg to 3.2 digits, mmHg to 3.1 digit.
- Conversion error corrected. Thanks Frank.

**Comment by Delta-99** [comment]
Going to assume this is fixed and close this one.
