### ISSUE TITLE
Enhancement idea : Change AI A2A planes behavior

### ISSUE THREAD

**Issue by Ked57** [FlightControl-Master/MOOSE#845]
So i've been thinking about a thing we could do about AI, everything is described here : https://docs.google.com/document/d/1-wkanPKQxSwxlfKOvPQMJahuq8a2h_62bIcdwOBO1MY/edit?usp=sharing

**Comment by thebgpikester** [comment]
The doc describes (some of) the AI process in the _core_ game.
MOOSE only handles the use of open interface LUA functions that are publicly open such as those listed on Hoggit and the old ED wiki. AI is not directly and in realtime accessible through those functions, only the higher level TASK part of a units advanced waypoint actions.

Check out the following resources for things you can alter:

1.  http://wiki.hoggit.us/view/Category:Singleton_Functions
2.  http://wiki.hoggit.us/view/Category:Class_Functions
3.  <Game install API docs> e.g. C:\Program Files\Eagle Dynamics\DCS World OpenBeta\API\DCS_ControlAPI.html
4. Advanced waypoint actions of the Mission editor (docs under game install)

Cranking/notching is at a level lower than the task "Engage", you can influence "Engage" via the Advanced Waypoint actions such as Missile rules like NEZ firing, max range firing and so on, but those are limited.

Once you let an aircraft engage, if it's not in the advanced actions, you can't change it.

**Comment by Ked57** [comment]
I was thinking about that : MOOSE handles the defensive and approaching phase because of what is required for them : notching and crancking can be achieved through waypoints via MOOSE am i right ? 
Engage being just the CAP task added to the group. You have a resetTask() function in the second link you mentionned so it shouldn't be a problem

**Comment by thebgpikester** [comment]
Well here's the thing. you can't have it following waypoints and have a CAP task or any other air to air other than AI:off, because it simply ignores waypoints from then on. If you want to recreate Air combat (or at least BVR) completely and do it with waypoints, the AI has to be off. If the AI is off and you don't handle every single element of air combat (between ranges) then the AI will act stupid. It's painful enough watching the enforced border zone with AI:Off. What does it do with two elements approaching from different directions? How do you handle all the possible permutations without melting the PC and being on a project for more than a year? It seems to me out of scope and I've got some knowledge of handling ground units which are much slower, but far be for me to burst that balloon, it's certainly something I would love to see, I just don't see the complexity being achievable, seems like it's something needed in the core game itself.

**Comment by thebgpikester** [comment]
I'd rather even see an oval cap zone first, that's been hard enough to see in DCS.

**Comment by Ked57** [comment]
I agree about the fact that it should be in DCS Core, but you can remove the CAP task while not engaging right ? I think it's possible

**Comment by Delta-99** [comment]
I would have to agree with Pikey here that this (or most of it) sounds out of scope. You can probably spend two months of development on something like this just to find out that its not possible anyway or its even wonkier than whats built into DCS. One just doesn't have the API access or really much that can be done with the AI for this kind of thing. If it was something like Arma3 engine you can get down to this type of level using FSM's or something perhaps. Even then only so much you can do.

From what I see the AI is not as DUMB as most seem to indicate. At least in my opinion. Yes, at times they do some really dumb things but for the most part they are not bad depending on airframe etc etc.
