### ISSUE TITLE
AID: SetSquadronLandingAtEngineShutdown destroys the aircraft at touchdown

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#875]
Expected: the AI should land, taxi and shutdown and then be destroyed() with this setting.
Observed: The AI are destroyed at the moment the LAND event is fired, or when their wheels touch.

Not sure if this was intentional or not as I recall issues with taxiing aircraft etc., so maybe a feature.

**Comment by funkyfranky** [comment]
Do know the exact circumstances in your case. But it sounds familiar...

When the airbase does not have a valid parking spot for the AI aircraft, they get despawned the moment they land. That is the way DCS(!) handles the problem.

It can happen on many (medium to small) airports on NTTR for example - mostly for non-fighter aircraft.

Try to put the aircraft type on the airport with a ramp start to see if it has a valid parking spot there. If not it will be despawned when it lands on that airport.

**Comment by thebgpikester** [comment]
Unfortunately AID manages all the spawning, but I will compare airports and see if there is a trend or different behavior.

**Comment by jtoppins** [comment]
This issue appears to be due to this commit:

`
commit ea96a5e0a38bd030a0e582fc4f7a3870b45d1cb1
Author: FlightControl_Master <sven.van.de.velde@telenet.be>
Date:   Wed Aug 30 07:30:03 2017 +0200

    Planes remaining at airfield fixed
`

While the change was well intended the change in AI_A2A_DISPATCHER:OnEventLand() will always be executed. Which is incorrect from the original intent, to remove units whom land at airbases that are not theirs and then get stuck. The problem with the logic is, as best I under stand it, an RTB command will not be issued until the fuel threshold is reached. Therefore the check will always be true resulting the the unit always being deleted on landing regardless of if the unit landed at the correct airbase or not.

Solutions:
1. To handle the landing at an incorrect base the check should be against the unit's home base and the current base.
-or-
2. Check against some minimum hard coded fuel threshold however I am not sure what the resolution of the floating point value is and one would want to compare against something relatively small like 0.001.
-or-
3. Register an OnEngineShutdown() handler to delete the unit if the unit runs out of fuel while taxiing.

**Comment by FlightControl-User** [comment]
Wow! Thanks. I'll check.

**Comment by thebgpikester** [comment]
3. Mind OnEngineShutdown() also fires if the plane is in the air and was hit and lost and engine. check the UNIT:InAir() first!!! else disappearing damaged shoot downs.

**Comment by jtoppins** [comment]
I should mention I tested the proposed change on top of tag 2.3.1_-_New_Mark_Events but posted for pulling into develop.

**Comment by thebgpikester** [comment]
It makes sense although I've not been able to reproduce, since the code has changed the original Bug is invalid and should be opened as a new issue if it recurs on the new code.
