### ISSUE TITLE
TAD-CGO-008 Map markers for tasks not showing in MP or SP

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#888]
Map marker option for tasks not showing in MP or SP.

**Comment by Delta-99** [comment]
See #998 (likely same issue)

**Comment by FlightControl-User** [comment]
@Delta-99 @shadowze This is a structural problem in the code...
I need to rework the TaskInfo methods and right now this is too much. I've done a very preliminary fix for the moment. The marks show, but not with much details per coordinate. I need to implement the methods of TaskInfo allowing to add a collection of information, so that marking can be done per coordinate within the task objectives, which is to deploy a set cargo.

I will keep this post open and will move this to the future for a fix.

**Comment by shadowze** [comment]
ok thanks

**Comment by baluballa** [comment]
Overdue...
