### ISSUE TITLE
DETECTION_MANAGER needs to become part of TASK_MANAGER

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#900]

**Comment by thebgpikester** [comment]
I'm not fond of detection being the instigator of all Task creation. It rules out complex detection or no detections.
For example. Infantry wont spot a ship
Nothing will spot a static
Nothing will spot scenery.

It also has hangups with moose detection because of night time affects and range. Predators go out of control, a soldier cant spot a unit (even if it's a 100ft high building unit) in the dark for ages.

Detection is great, but its limiting Task flexibility.

**Comment by Delta-99** [comment]
I think I agree with @thebgpikester on this one. I'm not sure why DETECTION needs to be part of TASK. Seem to be two completely separate things. Yes, DETECTION can feed a TASK like it does now but it doesn't always have to I don't think. And TASKS can / should work without DETECTION. That is programmatically created TASKS.

Would like to hear why @FlightControl-User thinks this is necessary. No description because he probably has all this info in his head ;)

**Comment by FlightControl-User** [comment]
i don't remember anymore what i mean with this, closing.
