### ISSUE TITLE
A2ADispatcher: No cleanup at airports causes stall

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#906]
When aircraft have an ATC taxi hiccup, or they get stuck for a silly DCS reason, there is no method to despawn them and so the dispatcher doesn't continue dealing with issues because it has a live plane and thus the entire situation is stalled and stuck.

With a new DLC map like Persian Gulf these things happen more often.

The solution should probably be in A2ADispatcher: Cleanup(120) or similar like spawn has built in. However possible to add it to the Cleanup class or another way?

**Comment by jtoppins** [comment]
An alternative would be to set timeouts for both takeoff and EngineShutdown events. A simple example:

- Unit A spawned and an OnEngineStart event handler is registered
- Once Unit A starts engines a takeoff event handler is registered for unit and a timer of 10 minutes is started (scheduled function)
- On takeoff the event handler writes **atomically** a bit noting the unit has taken off already, discussion later
  - when the scheduled function runs it will check for this bit, if not set it will delete the unit and cancel the task

The process for handling returning aircraft is generally the same:
- register a land event handler
- once land fires schedule a timeout, we don't really need to handle the engine shutdown event because we are going to delete the unit anyway so just let the timeout expire and delete the unit regardless of the status of the unit

## Discussion
The write of the status bit must be atomic otherwise this is a race condition between the scheduled timeout and the event happening. My understanding is event processing must complete within a single frame which seems to satisfy this atomic requirement.

**Comment by thebgpikester** [comment]
If I'm honest, the ten minute timer for post birth and pre T/O and the the same for post Land and pre engine shutdown should be way more reliable than current. There's some state that AI get into when they collided with themselves, not damaged and somehow moving but not moving that prevents InitCleanUp() processing. I'd be well supportive of this type of approach. I'd even consider just coding it separately as it shouldn't be hard to do, however, it's supposed to be working in moose so it should be.

**Comment by thebgpikester** [comment]
Encountered this last night, Dispatcher cannot understand if a GCI is stalled taxiing. You can recreate this by shutting down the runway (single bomb on runway), you get a long queue of aircraft keeps spawning, there is no spawn control or cleanup, it just disregards every plane it loses control over.

This becomes a problem when you are overhead and trying to kill targets around it. You get continuous spawns trying to intercept you but unable, taxiing, getting stuck because AI wont takeoff on a broken runway.

Can't think of a fix tbh, it's just a generic flaw in design between MOOSE and DCS. You could detect the runway breaking, but would require an event handler for every runway death event, probably a little excessive, i hate event handlers.

Not sure how Moose knows about planes it cannot control, or if there is a valid check that could be made. This will have to be in permanenet workaround state.

**Comment by thebgpikester** [comment]
Or the cleanup is added to dispatcher airplanes.... ofc

**Comment by Delta-99** [comment]
One thing that Moose can perhaps do to help with this is track how many planes have been spawned via the Dispatcher vs. how many have been able to take off. Assume if they aren't taking off there is a taxi issue. So, Moose won't spawn anymore. What is done beyond that I'm not sure!!!

Its not like ED is ever going to create a flag anywhere indicating the airport / runway is unusable at the moment.

**Comment by baluballa** [comment]
@thebgpikester can you update on this... Moose or DCS bug?

**Comment by thebgpikester** [comment]
DCS "thing"
