### ISSUE TITLE
A2A_Dispatcher: GCI can launch and attack it's own side.

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#965]
No idea how to replicate, yet.
https://youtu.be/7SCygj9HWPw?t=1m16s

**Comment by thebgpikester** [comment]
DetectionSetGroup = SET_GROUP:New()
DetectionSetGroup:FilterPrefixes( { "[RedEWR]" } )
DetectionSetGroup:FilterStart()

Detection = DETECTION_AREAS:New( DetectionSetGroup, 30000)
A2ADispatcher = AI_A2A_DISPATCHER:New( Detection )
--RedBorderZone = ZONE_POLYGON:New( "Red Border", GROUP:FindByName("[Red Border]"))
--A2ADispatcher:SetBorderZone(RedBorderZone)

A2ADispatcher:SetTacticalDisplay( true )
A2ADispatcher:SetSquadron("K1","Kutaisi", { "[KutaisiCAP]" }, 100)
--A2ADispatcher:SetSquadronCap("Kutaisi",RedBorderZone,1000,40000,500,600,800,900,"BARO")
A2ADispatcher:SetSquadronGci( "K1", 900, 1200 )
A2ADispatcher:SetSquadronOverhead( "K1", 1 )
A2ADispatcher:SetDefaultGrouping( 4 )
A2ADispatcher:SetDefaultTakeoffInAirAltitude( 500 )
A2ADispatcher:SetDefaultLandingAtRunway()

**Comment by Delta-99** [comment]
So one of the ways I can see this happening is that Moose CGI is setting specific targets using an EnRouteTask assignment. If DCS accepts its own side as a target then this might be what is going on. Can probably test this in ME only by setting that and seeing what happens.

If CGI works this way then that is what I would look towards in order to debug.

**Comment by lastresort77** [comment]
[test1.zip](https://github.com/FlightControl-Master/MOOSE/files/2220420/test1.zip)

**Comment by FlightControl-User** [comment]
This is the most weird report i've ever seen.

**Comment by FlightControl-User** [comment]
Closing until this pops up again.
